"use strict";
/**
 * BidBuddy Roofing SMS Handler
 * Complete replacement file for lib/smsHandler.js
 *
 * ARCHITECTURE:
 * Compliance (STOP/HELP/START) and pricing math are 100% deterministic,
 * rule-based code. These are never generated by AI, for legal/accuracy
 * reasons - carrier keyword compliance and dollar figures must never
 * drift or be invented.
 *
 * The actual REPLY TEXT is generated conversationally by OpenAI
 * (lib/aiReply.js + lib/promptBuilder.js), grounded strictly in the
 * deterministic job state and computed estimate.
 *
 * If OPENAI_API_KEY is not set, or the OpenAI call fails/times out for
 * any reason, this file automatically falls back to the previous
 * template-based reply system (classifyIntent + buildReply) so SMS
 * never goes silent in production.
 *
 * *** FIX #1 (cross-job customer name/address mixing) ***
 * Root cause of the Bluff City bug: when an estimator sent job A's
 * measurements, THEN job B's measurements (which auto-starts a second
 * thread and makes it active), and only THEN sent job A's customer
 * name/address in its own follow-up message, the old resolveActiveThread()
 * logic only ever considered bucket.activeThreadId when deciding which
 * thread to attach an orphan name/address to. That meant job A's name
 * silently landed on job B's dashboard row instead of job A's.
 *
 * This revision fixes it two ways:
 *   1. When a bare name/address message (no measurements) arrives and it
 *      does not match an existing customer by name or by address, EVERY
 *      thread on the phone that is still missing a name is now
 *      considered - not just the active one. If exactly one thread is
 *      missing a name, it is attached there correctly regardless of which
 *      thread is "active".
 *   2. If TWO OR MORE threads are missing a name at the same time (the
 *      genuinely ambiguous case), the system no longer guesses. It sends
 *      one short clarifying question ("job 1 or job 2?") and holds the
 *      name/address until the estimator answers.
 *
 * *** FIX #2 (silent persistence failures / no visibility) ***
 * Previously, persistToDatabase() only ever logged on the DB-error path
 * (a thrown exception from saveEstimate/updateEstimate). Every OTHER way
 * this function could fail to write a row - estimatorContext being
 * null/false (phone never resolved to a registered company), dbModule
 * failing to load at boot, or dbModule missing the expected functions -
 * produced ZERO log output, making "why isn't anything in the dashboard"
 * impossible to diagnose from Render logs alone. This revision adds
 * explicit console.log calls on every skip path AND on every successful
 * insert/update, so Render logs now always show exactly what happened on
 * every inbound message, whether it saved, why it didn't, or that it did.
 *
 * Expected usage from an Express route:
 *   const { handleSms } = require("./lib/smsHandler");
 *   app.post("/sms", handleSms);
 */

const fs = require("fs");
const path = require("path");

let aiReplyModule = null;
try {
  aiReplyModule = require("./aiReply");
} catch (_) {
  aiReplyModule = null;
}

// -----------------------------------------------------------------------------
// Optional pricing module loading (lib/roofingPricing.js — the real engine)
// -----------------------------------------------------------------------------

let pricingModule = null;
const pricingModuleCandidates = [
  "./roofingpricing",
  "./roofingPricing",
  "./pricing",
  "../lib/roofingpricing",
  "../lib/roofingPricing",
  "../lib/pricing"
];

for (const candidate of pricingModuleCandidates) {
  try {
    pricingModule = require(candidate);
    break;
  } catch (_) {
    // Keep trying. This file can still produce useful conversations without it.
  }
}

// -----------------------------------------------------------------------------
// Optional multi-tenant DB loading (companies, users, pricing_profiles, shingles,
// and estimates persistence)
// -----------------------------------------------------------------------------

// *** FIX: HARD-PINNED PATH, NO FALLBACK CHAIN ***
// Root cause of the "nothing ever saves" bug: the previous version of this
// file tried a LIST of candidate paths in order ("./db" first, then "../db",
// etc.) and silently used whichever one loaded successfully. Since this file
// lives in lib/, the very first candidate "./db" resolves to lib/db.js - an
// old/stub file that happens to exist in this project alongside the REAL
// multi-tenant db module at db/index.js (project root). require("./db")
// loaded that stub successfully (so hasDbModule was true), but it has none
// of the real exports (getUserByPhone, getPricing, saveEstimate,
// updateEstimate, etc.) - so every persistence attempt silently no-op'd
// with hasSaveEstimateFn:false, on every company, every test, the entire
// time. This was NOT a parsing bug or a phone-mapping bug - it was this
// file quietly loading the wrong module.
//
// Fix: require ONLY the real path, with no ambiguous fallback list. If this
// path is ever wrong for your project layout, this will now fail LOUDLY at
// boot (a clear stack trace in Render logs) instead of silently falling
// back to some other file that happens to also be requireable.
let dbModule = null;
let dbLoadError = null;
try {
  dbModule = require("../db");
} catch (err) {
  dbLoadError = err;
}

// *** DIAGNOSTIC LOGGING: log DB module load status ONCE at startup, so a
// failed require (wrong path, missing dependency, etc.) shows up clearly in
// Render's boot logs instead of silently causing every later persistence
// attempt to no-op with no explanation. This also logs the RESOLVED FILE
// PATH that Node actually loaded, so if lib/db.js (or any other stray file)
// is ever accidentally required again in the future, it will be immediately
// obvious from this log line instead of requiring another multi-day
// debugging session. ***
if (dbModule) {
  let resolvedPath = null;
  try {
    resolvedPath = require.resolve("../db");
  } catch (_) {
    resolvedPath = "unknown";
  }
  console.log(
    "[BidBuddy SMS] db module loaded successfully.",
    JSON.stringify({
      resolvedPath,
      hasGetUserByPhone: typeof dbModule.getUserByPhone === "function",
      hasGetPricing: typeof dbModule.getPricing === "function",
      hasSaveEstimate: typeof dbModule.saveEstimate === "function",
      hasUpdateEstimate: typeof dbModule.updateEstimate === "function",
      hasGetCompany: typeof dbModule.getCompany === "function"
    })
  );
  if (typeof dbModule.saveEstimate !== "function") {
    console.error(
      "[BidBuddy SMS] WARNING: db module loaded from",
      resolvedPath,
      "but has NO saveEstimate function. Nothing will ever be persisted to the dashboard until this is fixed. Check for a stray file shadowing the real db module."
    );
  }
} else {
  console.error(
    "[BidBuddy SMS] db module FAILED TO LOAD from ../db. No estimate will ever be persisted to the dashboard until this is fixed.",
    dbLoadError ? String(dbLoadError.message || dbLoadError) : "unknown error"
  );
}

function resolveEstimatorContext(fromPhone) {
  if (!dbModule || typeof dbModule.getUserByPhone !== "function") {
    console.log("[BidBuddy SMS] resolveEstimatorContext: db module or getUserByPhone unavailable - treating as unregistered number.");
    return null;
  }
  try {
    const user = dbModule.getUserByPhone(fromPhone);
    if (!user) {
      console.log(`[BidBuddy SMS] resolveEstimatorContext: no user found for phone ${normalizePhone(fromPhone)} - treating as unregistered number.`);
      return null;
    }
    const pricing = typeof dbModule.getPricing === "function" ? dbModule.getPricing(user.company_id) : null;
    if (!pricing) {
      console.log(`[BidBuddy SMS] resolveEstimatorContext: user found (company_id=${user.company_id}) but no pricing profile exists for that company - treating as unregistered number.`);
      return null;
    }
    return { user, companyId: user.company_id, companyName: user.company_name, pricing };
  } catch (err) {
    console.error("[BidBuddy SMS] resolveEstimatorContext threw an error.", err);
    return null;
  }
}

function resolveShingle(estimatorContext, materialText) {
  if (!estimatorContext || !dbModule) return null;
  try {
    if (materialText && typeof dbModule.matchShingle === "function") {
      const matched = dbModule.matchShingle(estimatorContext.companyId, materialText);
      if (matched) return matched;
    }
    if (typeof dbModule.getDefaultShingle === "function") {
      return dbModule.getDefaultShingle(estimatorContext.companyId);
    }
  } catch (_) {
    // fall through
  }
  return null;
}

function mapJobForPricingEngine(job) {
  return {
    squares: job.squares,
    layers: job.tearOffLayers,
    pitch: parsePitchNumber(job.pitch),
    stories: job.stories,
    ridge_lf: job.ridgeLf,
    eave_lf: job.eaveRakeLf,
    valley_lf: job.valleyLf,
    penetrations: job.pipeBoots || job.penetrations,
    chimneys: job.chimneys,
    skylights: job.skylights,
    // Feeds roofingPricing.js's own dumpster inclusion logic directly, so
    // there is exactly ONE place (the real pricing engine) that decides
    // whether the dumpster fee is charged - never a second, separate adder
    // bolted on afterward, which previously double-billed it.
    dumpster_excluded: job.dumpsterRequested === false
  };
}

// -----------------------------------------------------------------------------
// Compliance: STOP / HELP / START keyword handling — deterministic, unchanged
// -----------------------------------------------------------------------------

const OPT_OUT_KEYWORDS = ["STOP", "UNSUBSCRIBE", "CANCEL"];
const OPT_IN_KEYWORDS = ["START", "YES"];
const HELP_KEYWORDS = ["HELP"];

const OPT_IN_MESSAGE =
  "You have agreed to receive SMS updates from BidBuddy USA LLC. Msg freq may vary. Std msg & data rates apply. Reply STOP to opt out, HELP for help.";
const OPT_OUT_MESSAGE =
  "BidBuddy USA LLC: You have been unsubscribed and will no longer receive messages from us. Reply HELP for assistance.";
const HELP_MESSAGE =
  "BidBuddy USA LLC: For help, reply HELP or contact us at +19012889044. Msg frequency varies. Msg&data rates may apply. Reply STOP to opt out.";

function matchesKeyword(cleanedText, keywordList) {
  const normalized = String(cleanedText || "")
    .trim()
    .replace(/[.!?,;:]+$/g, "")
    .toUpperCase();
  return keywordList.includes(normalized);
}

// -----------------------------------------------------------------------------
// Opt-out persistence: database-backed (survives redeploys/restarts), with a
// local JSON file used ONLY as an automatic fallback if the database call
// throws.
// -----------------------------------------------------------------------------

const OPT_OUT_STATE_FILE =
  process.env.BIDBUDDY_OPTOUT_STATE_FILE ||
  path.join(process.env.BIDBUDDY_DATA_DIR || path.join(process.cwd(), "data"), "sms-optouts.json");

function ensureDataDirFor(filePath) {
  const dir = path.dirname(filePath);
  try {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  } catch (_) {
    // Read-only filesystem fallback: in-memory only for this process lifetime.
  }
}

function loadOptOutState() {
  try {
    ensureDataDirFor(OPT_OUT_STATE_FILE);
    if (!fs.existsSync(OPT_OUT_STATE_FILE)) return {};
    const raw = fs.readFileSync(OPT_OUT_STATE_FILE, "utf8");
    return JSON.parse(raw || "{}");
  } catch (_) {
    return {};
  }
}

function saveOptOutState(state) {
  try {
    ensureDataDirFor(OPT_OUT_STATE_FILE);
    fs.writeFileSync(OPT_OUT_STATE_FILE, JSON.stringify(state, null, 2));
  } catch (_) {
    // Do not fail SMS response if state save fails.
  }
}

let optOutState = loadOptOutState();

function hasDbOptOutSupport() {
  return Boolean(
    dbModule &&
      typeof dbModule.isPhoneOptedOut === "function" &&
      typeof dbModule.recordOptOut === "function" &&
      typeof dbModule.recordOptIn === "function"
  );
}

function isOptedOut(phone) {
  if (hasDbOptOutSupport()) {
    try {
      return dbModule.isPhoneOptedOut(phone);
    } catch (_) {
      // fall through to JSON fallback below
    }
  }
  const key = normalizePhone(phone);
  return Boolean(optOutState[key] && optOutState[key].optedOut);
}

function recordOptOut(phone, companyId) {
  if (hasDbOptOutSupport()) {
    try {
      dbModule.recordOptOut(phone, companyId || null);
      return;
    } catch (_) {
      // fall through
    }
  }
  const key = normalizePhone(phone);
  optOutState[key] = optOutState[key] || {};
  optOutState[key].optedOut = true;
  optOutState[key].optedOutAt = new Date().toISOString();
  saveOptOutState(optOutState);
}

function recordOptIn(phone, companyId) {
  if (hasDbOptOutSupport()) {
    try {
      dbModule.recordOptIn(phone, companyId || null);
      return;
    } catch (_) {
      // fall through
    }
  }
  const key = normalizePhone(phone);
  optOutState[key] = optOutState[key] || {};
  optOutState[key].optedOut = false;
  optOutState[key].optedInAt = new Date().toISOString();
  saveOptOutState(optOutState);
}

// -----------------------------------------------------------------------------
// Lightweight context store
// -----------------------------------------------------------------------------

const DATA_DIR = process.env.BIDBUDDY_DATA_DIR || path.join(process.cwd(), "data");
const STATE_FILE = process.env.BIDBUDDY_SMS_STATE_FILE || path.join(DATA_DIR, "sms-conversations.json");
const MAX_STORED_MESSAGES = 20;
const MAX_AI_HISTORY_TURNS = 8;
const MAX_THREADS_PER_PHONE = Number(process.env.BIDBUDDY_MAX_THREADS_PER_PHONE || 25);

function ensureDataDir() {
  try {
    if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  } catch (_) {
    // read-only fallback: in-memory only
  }
}

function loadState() {
  try {
    ensureDataDir();
    if (!fs.existsSync(STATE_FILE)) return {};
    const raw = fs.readFileSync(STATE_FILE, "utf8");
    return JSON.parse(raw || "{}");
  } catch (_) {
    return {};
  }
}

function saveState(state) {
  try {
    ensureDataDir();
    fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
  } catch (_) {
    // Do not fail SMS response if state save fails.
  }
}

let conversationState = loadState();

function normalizePhone(phone) {
  return String(phone || "unknown")
    .trim()
    .replace(/[^+0-9]/g, "");
}

function getPhoneKey({ from, companyId }) {
  const normalized = normalizePhone(from);
  return `${companyId || "default"}:${normalized}`;
}

function makeThreadId() {
  return `t_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function emptyThread() {
  return {
    id: makeThreadId(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    job: emptyRoofJob(),
    messages: [],
    lastEstimate: null,
    askedForCustomerInfo: false,
    dbEstimateId: null,
    customerKey: null
  };
}

function getOrCreatePhoneBucket(key) {
  if (!conversationState[key]) {
    conversationState[key] = {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      estimatorContext: null,
      activeThreadId: null,
      threads: {},
      pendingAssignment: null
    };
  }
  const bucket = conversationState[key];
  if (!bucket.threads) {
    const migrated = emptyThread();
    migrated.job = bucket.job || emptyRoofJob();
    migrated.messages = bucket.messages || [];
    migrated.lastEstimate = bucket.lastEstimate || null;
    migrated.askedForCustomerInfo = Boolean(bucket.askedForCustomerInfo);
    migrated.dbEstimateId = bucket.dbEstimateId || null;
    migrated.customerKey = migrated.job.customerName ? normalizeCustomerKey(migrated.job.customerName) : null;
    conversationState[key] = {
      createdAt: bucket.createdAt || new Date().toISOString(),
      updatedAt: bucket.updatedAt || new Date().toISOString(),
      estimatorContext: bucket.estimatorContext || null,
      activeThreadId: migrated.id,
      threads: { [migrated.id]: migrated },
      pendingAssignment: null
    };
  }
  if (conversationState[key].pendingAssignment === undefined) {
    conversationState[key].pendingAssignment = null;
  }
  return conversationState[key];
}

function normalizeCustomerKey(name) {
  return String(name || "").trim().toLowerCase();
}

function normalizeAddressKey(address) {
  return String(address || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

function findThreadByCustomerName(bucket, name) {
  const key = normalizeCustomerKey(name);
  if (!key) return null;
  for (const threadId of Object.keys(bucket.threads)) {
    const t = bucket.threads[threadId];
    if (t.customerKey && t.customerKey === key) return t;
  }
  return null;
}

function findThreadByCustomerAddress(bucket, address) {
  const key = normalizeAddressKey(address);
  if (!key) return null;
  for (const threadId of Object.keys(bucket.threads)) {
    const t = bucket.threads[threadId];
    const tKey = normalizeAddressKey(t.job && t.job.customerAddress);
    if (tKey && tKey === key) return t;
  }
  return null;
}

function findThreadsNeedingCustomerName(bucket) {
  return Object.keys(bucket.threads)
    .map((id) => bucket.threads[id])
    .filter((t) => !t.customerKey && !(t.job && t.job.customerName))
    .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
}

function isThreadComplete(thread) {
  return Boolean(thread && thread.job && missingRequiredFields(thread.job).length === 0 && thread.lastEstimate);
}

function looksLikeNewJobStart(details) {
  return Boolean(details && details.squares !== undefined && details.squares !== null);
}

const CORE_MEASUREMENT_KEYS_FOR_BARE_CHECK = [
  "squares",
  "roofAreaSqFt",
  "pitch",
  "stories",
  "tearOffLayers",
  "material",
  "ridgeLf",
  "eaveRakeLf",
  "valleyLf",
  "chimneys",
  "skylights",
  "pipeBoots",
  "deckingSheets",
  "deckingSqFt"
];

function isBareCustomerInfoMessage(details) {
  if (!details) return false;
  if (!details.customerName && !details.customerAddress) return false;
  return !CORE_MEASUREMENT_KEYS_FOR_BARE_CHECK.some(
    (k) => details[k] !== undefined && details[k] !== null && details[k] !== ""
  );
}

function resolveActiveThread(bucket, cleaned, details) {
  const candidateName = (details && details.customerName) || extractCustomerName(cleaned);
  const candidateAddress = (details && details.customerAddress) || extractCustomerAddress(cleaned);

  if (candidateName) {
    const matchedByName = findThreadByCustomerName(bucket, candidateName);
    if (matchedByName) {
      bucket.activeThreadId = matchedByName.id;
      return matchedByName;
    }
  }

  if (candidateAddress) {
    const matchedByAddress = findThreadByCustomerAddress(bucket, candidateAddress);
    if (matchedByAddress) {
      bucket.activeThreadId = matchedByAddress.id;
      return matchedByAddress;
    }
  }

  if (candidateName) {
    const needingName = findThreadsNeedingCustomerName(bucket);
    if (needingName.length === 1) {
      const only = needingName[0];
      only.customerKey = normalizeCustomerKey(candidateName);
      bucket.activeThreadId = only.id;
      return only;
    }
    const fresh = emptyThread();
    fresh.customerKey = normalizeCustomerKey(candidateName);
    bucket.threads[fresh.id] = fresh;
    bucket.activeThreadId = fresh.id;
    return fresh;
  }

  const active = bucket.activeThreadId ? bucket.threads[bucket.activeThreadId] : null;
  if (!active) {
    const fresh = emptyThread();
    bucket.threads[fresh.id] = fresh;
    bucket.activeThreadId = fresh.id;
    return fresh;
  }

  if (!isThreadComplete(active)) {
    return active;
  }

  if (looksLikeNewJobStart(details)) {
    const fresh = emptyThread();
    bucket.threads[fresh.id] = fresh;
    bucket.activeThreadId = fresh.id;
    return fresh;
  }

  return active;
}

function pruneOldThreads(bucket) {
  const ids = Object.keys(bucket.threads);
  if (ids.length <= MAX_THREADS_PER_PHONE) return;
  const removable = ids
    .filter((id) => id !== bucket.activeThreadId && isThreadComplete(bucket.threads[id]))
    .sort((a, b) => new Date(bucket.threads[a].updatedAt).getTime() - new Date(bucket.threads[b].updatedAt).getTime());
  let overflow = ids.length - MAX_THREADS_PER_PHONE;
  for (const id of removable) {
    if (overflow <= 0) break;
    delete bucket.threads[id];
    overflow--;
  }
}

function emptyRoofJob() {
  return {
    trade: "roofing",
    customerName: null,
    customerAddress: null,
    squares: null,
    roofAreaSqFt: null,
    pitch: null,
    stories: null,
    access: null,
    tearOffLayers: null,
    material: null,
    complexity: null,
    ridgeLf: null,
    eaveRakeLf: null,
    valleyLf: null,
    chimneys: null,
    skylights: null,
    pipeBoots: null,
    penetrations: null,
    deckingSheets: null,
    deckingSqFt: null,
    deckingCondition: null,
    dumpAccess: null,
    dumpsterRequested: null,
    permitRequired: null,
    ventilation: null,
    flashingScope: null,
    notes: []
  };
}

// -----------------------------------------------------------------------------
// Incoming SMS parsing helpers
// -----------------------------------------------------------------------------

function getTelnyxEventType(body) {
  return body && body.data && body.data.event_type ? body.data.event_type : null;
}

function isProcessableInboundEvent(body) {
  const eventType = getTelnyxEventType(body);
  if (eventType === null) return true;
  return eventType === "message.received";
}

function extractSmsPayload(req) {
  const body = req && req.body ? req.body : {};

  const telnyxPayload = body.data && body.data.payload ? body.data.payload : null;
  if (telnyxPayload) {
    return {
      from: telnyxPayload.from && telnyxPayload.from.phone_number,
      to: telnyxPayload.to && telnyxPayload.to.length ? telnyxPayload.to[0].phone_number : undefined,
      text: telnyxPayload.text || telnyxPayload.body || "",
      provider: "telnyx",
      eventType: getTelnyxEventType(body),
      raw: body
    };
  }

  return {
    from: body.From || body.from || body.sender || body.phone || body.msisdn,
    to: body.To || body.to || body.recipient,
    text: body.Body || body.body || body.text || body.message || "",
    provider: body.provider || "unknown",
    eventType: null,
    raw: body
  };
}

function cleanText(text) {
  return String(text || "")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function lower(text) {
  return cleanText(text).toLowerCase();
}

function numberFromMatch(match) {
  if (!match || !match[1]) return null;
  const n = Number(String(match[1]).replace(/,/g, ""));
  return Number.isFinite(n) ? n : null;
}

function titleCase(str) {
  return String(str || "")
    .toLowerCase()
    .replace(/\b([a-z])/g, (c) => c.toUpperCase());
}

const CUSTOMER_NAME_RE =
  /\b(?:this is for customer|for customer|customer(?:'s)? name is|customer name|customer is|customer:)\s+([A-Za-z][A-Za-z'.-]*(?:\s+[A-Za-z][A-Za-z'.-]*){0,3})/i;

const NAME_TRAILING_STOPWORDS = new Set(["at", "on", "near", "address", "is", "for", "and", "located"]);

const NAME_LEADING_REJECT_WORDS = new Set([
  "supplying", "providing", "bringing", "using", "getting", "renting",
  "paying", "handling", "taking", "doing", "going", "not", "already",
  "still", "unknown", "unsure", "waiting", "responsible",
  "aware", "ok", "okay", "fine", "good", "happy", "unhappy"
]);

function extractCustomerName(text) {
  const m = String(text || "").match(CUSTOMER_NAME_RE);
  if (!m) return null;
  let words = m[1]
    .trim()
    .replace(/[,.]+$/, "")
    .split(/\s+/);
  while (words.length && NAME_TRAILING_STOPWORDS.has(words[words.length - 1].toLowerCase())) {
    words.pop();
  }
  if (!words.length) return null;
  if (NAME_LEADING_REJECT_WORDS.has(words[0].toLowerCase())) return null;
  const name = words.join(" ").trim();
  return name ? titleCase(name) : null;
}

// Also matches customer names given as a simple appositive after
// measurements, e.g. "...architectural shingles Kristy Smith customer 313
// Johnsborough drive" - a name (1-3 capitalized-looking words) immediately
// followed by the word "customer". This is the phrasing pattern real
// estimators actually use in the field (name stated, THEN labeled).
// NOTE: deliberately case-SENSITIVE (no /i flag) and requires each captured
// word to START WITH AN UPPERCASE LETTER. This is what actually
// distinguishes a real name ("Kristy Smith") from job-description words
// that happen to precede it in a run-on message ("...architectural
// shingles Kristy Smith customer 313 Johnsborough drive") - estimators
// consistently type job-scope terms lowercase and capitalize customer
// names, even in otherwise all-lowercase texts. Capping at 2 words (not 3)
// also reduces the chance of accidentally swallowing an extra capitalized
// word from earlier in the message.
const NAME_THEN_CUSTOMER_LABEL_RE = /\b([A-Z][a-zA-Z'.-]*(?:\s+[A-Z][a-zA-Z'.-]*){0,1})\s+customer\b/;

// *** FIX #3 (name-first phrasing not recognized - the Kim Ellis bug) ***
// Root cause of the blank customer_name/job_address rows: an estimator
// phrased the customer info as "Kim Ellis is customer address 32
// Johnsborough Cove" - the name FIRST, then "is customer" as the label,
// with the word "is" (and optionally "the") sitting between the name and
// the word "customer". Neither CUSTOMER_NAME_RE ("for customer NAME") nor
// NAME_THEN_CUSTOMER_LABEL_RE ("NAME customer" with nothing in between)
// matches this phrasing, so extractCustomerNameLoose() silently returned
// null and the estimate was persisted with no customer_name at all. This
// adds that exact phrasing as a third recognized pattern, same
// capitalization-based heuristic as NAME_THEN_CUSTOMER_LABEL_RE above.
const NAME_IS_CUSTOMER_RE = /\b([A-Z][a-zA-Z'.-]*(?:\s+[A-Z][a-zA-Z'.-]*){0,1})\s+is\s+(?:the\s+)?customer\b/;

// Known job-scope/measurement words that should never be treated as part of
// a customer name, even if a user happens to capitalize them. Used as a
// last-line safety net on top of the capitalization heuristic above.
const NAME_REJECT_ANYWHERE = new Set([
  "shingles", "shingle", "story", "stories", "pitch", "squares", "square",
  "layer", "layers", "tear", "off", "roof", "architectural", "metal",
  "tile", "slate", "designer"
]);

function extractCustomerNameLoose(text) {
  const direct = extractCustomerName(text);
  if (direct) return direct;
  const raw = String(text || "");
  // *** FIX #3: try "NAME customer" first, then fall back to the new
  // "NAME is (the) customer" pattern, so both phrasings are covered. ***
  let m = raw.match(NAME_THEN_CUSTOMER_LABEL_RE);
  if (!m) m = raw.match(NAME_IS_CUSTOMER_RE);
  if (!m) return null;
  const words = m[1].trim().split(/\s+/);
  if (!words.length) return null;
  if (NAME_LEADING_REJECT_WORDS.has(words[0].toLowerCase())) return null;
  if (words.some((w) => NAME_REJECT_ANYWHERE.has(w.toLowerCase()))) return null;
  const name = words.join(" ").trim();
  return name ? titleCase(name) : null;
}

// *** FIX #4 (address suffix list too narrow + no trailing word boundary -
// the second half of the Kim Ellis bug) ***
// Root cause part A: "32 Johnsborough Cove" was never recognized because
// "cove" was not in STREET_SUFFIX at all - the regex had nothing to match
// against, so extractCustomerAddress() returned null and job_address was
// persisted blank. Expanded the suffix list to cover the common suffixes
// actually seen on residential streets (cove, trace, loop, bend, pointe,
// landing, run, crossing, pass, terrace, and many more), in addition to
// the original set.
//
// Root cause part B (a separate, more dangerous latent bug found while
// fixing part A): with no boundary required immediately after the suffix
// alternation, the suffix list could match as a bare PREFIX of an
// unrelated word later in the same message - e.g. "st" (street) matching
// just the first two letters of "story" - silently consuming the rest of
// that word plus everything after it into the address capture (via the
// trailing "city name" group) as garbage. This does NOT just affect Kim
// Ellis - any company/tenant whose message phrasing happens to place a
// word like "story", "state", "stories", etc. before the real street name
// could have gotten a garbage address silently saved instead of a blank
// one. Adding a required \b right after the suffix alternation forces it
// to end at an actual word boundary (whitespace, punctuation, or end of
// string), so it can no longer match mid-word.
const STREET_SUFFIX =
  "(?:street|st|avenue|ave|road|rd|drive|dr|lane|ln|court|ct|boulevard|blvd|way|place|pl|circle|cir|trail|trl|parkway|pkwy|highway|hwy|" +
  "cove|cv|trace|trce|loop|lp|bend|bnd|pointe|point|pt|landing|lndg|run|crossing|xing|pass|terrace|ter|row|walk|path|square|sq|" +
  "hollow|holw|manor|mnr|village|vlg|meadow|meadows|mdws|ridge|rdg|glen|grove|grv|heights|hts|knoll|knl|orchard|orch|park|pk|" +
  "plaza|plz|ranch|rnch|shores|shore|shr|springs|spgs|spring|spg|station|sta|summit|smt|valley|vly|view|vw|gardens|gdns|" +
  "extension|ext|crest|bluff|bluffs|estates|est|forest|frst|garden|gdn|harbor|hbr|isle|junction|jct|lake|lk|lakes|lks|" +
  "mount|mtn|neck|pike|plains|pln|port|shoal|shls|spur|turnpike|tpke|vale|vista|vis|wells|wls|mews)";
const ADDRESS_RE = new RegExp(
  "\\b(\\d{1,6}\\s+[A-Za-z0-9][A-Za-z0-9.'-]*(?:\\s+[A-Za-z0-9][A-Za-z0-9.'-]*){0,4}\\s+" +
    STREET_SUFFIX +
    "\\b" +
    "\\.?" +
    "(?:\\s*,?\\s*[A-Za-z][A-Za-z\\s]{1,24})?(?:\\s*,?\\s*[A-Za-z]{2})?(?:\\s*\\d{5}(?:-\\d{4})?)?)",
  "i"
);

function extractCustomerAddress(text) {
  const m = String(text || "").match(ADDRESS_RE);
  if (!m) return null;
  return m[1].trim().replace(/\s+/g, " ");
}

function parseRoofDetails(text) {
  const msg = lower(text);
  const details = {};
  const notes = [];

  let m = msg.match(/(?:^|\b)(\d+(?:\.\d+)?)\s*(?:squares|square|sqrs|sqs|sq)\b/);
  if (m) details.squares = numberFromMatch(m);

  m = msg.match(/(?:^|\b)(\d{3,6}(?:\.\d+)?)\s*(?:sf|sqft|sq ft|square feet)\b/);
  if (m) {
    details.roofAreaSqFt = numberFromMatch(m);
    if (!details.squares) details.squares = Math.round((details.roofAreaSqFt / 100) * 10) / 10;
  }

  m = msg.match(/\b(\d{1,2})\s*\/\s*12\b/);
  if (m) details.pitch = `${m[1]}/12`;
  if (!details.pitch) {
    m = msg.match(/\b(\d{1,2})\s*(?:pitch|slope)\b/);
    if (m) details.pitch = `${m[1]}/12`;
  }

  if (/\b(one|1)[ -]?(story|storey)\b/.test(msg) || /\bsingle story\b/.test(msg)) details.stories = 1;
  if (/\b(two|2)[ -]?(story|storey)\b/.test(msg)) details.stories = 2;
  if (/\b(three|3)[ -]?(story|storey)\b/.test(msg)) details.stories = 3;

  if (/\bsteep\b/.test(msg)) details.access = "steep";
  if (/\bwalkable\b/.test(msg)) details.access = "walkable";
  if (/\bhard access|tight access|bad access|limited access\b/.test(msg)) details.access = "limited";

  m = msg.match(/\b(\d+)\s*(?:layer|layers)\b/);
  if (m && /tear ?off|remove|existing|old roof|shingle/.test(msg)) details.tearOffLayers = numberFromMatch(m);
  if (/\bone layer\b/.test(msg) && /tear ?off|remove|existing|old roof|shingle/.test(msg)) details.tearOffLayers = 1;
  if (/\btwo layers\b/.test(msg) && /tear ?off|remove|existing|old roof|shingle/.test(msg)) details.tearOffLayers = 2;
  if (/\bno tear ?off|overlay|layover|recover\b/.test(msg)) details.tearOffLayers = 0;

  if (/\barchitectural|dimensional|30 year|laminate\b/.test(msg)) details.material = "architectural shingles";
  if (/\b3 tab|three tab|3-tab\b/.test(msg)) details.material = "3-tab shingles";
  if (/\bdesigner|premium|presidential|grand manor|carriage\b/.test(msg)) details.material = "designer shingles";
  if (/\bmetal|standing seam|r panel|corrugated\b/.test(msg)) details.material = "metal roofing";
  if (/\btile roof|clay tile|concrete tile\b/.test(msg)) details.material = "tile roofing";
  if (/\bslate\b/.test(msg)) details.material = "slate roofing";

  if (/\bsimple gable|straight gable|easy gable\b/.test(msg)) details.complexity = "simple";
  if (/\bhip roof\b/.test(msg)) details.complexity = "moderate";
  if (/\bcut up|cut-up|complex|lots of valleys|many valleys|dormers\b/.test(msg)) details.complexity = "complex";

  m = msg.match(/\b(\d+(?:\.\d+)?)\s*(?:lf|linear feet|feet|ft)\s*(?:of\s*)?(?:ridge|ridge cap)\b/);
  if (m) details.ridgeLf = numberFromMatch(m);
  m = msg.match(/\b(\d+(?:\.\d+)?)\s*(?:lf|linear feet|feet|ft)\s*(?:of\s*)?(?:eave|eaves|rake|rakes|eave rake|eave\/rake)\b/);
  if (m) details.eaveRakeLf = numberFromMatch(m);
  m = msg.match(/\b(\d+(?:\.\d+)?)\s*(?:lf|linear feet|feet|ft)\s*(?:of\s*)?(?:valley|valleys)\b/);
  if (m) details.valleyLf = numberFromMatch(m);

  m = msg.match(/\b(\d+)\s*(?:chimney|chimneys)\b/);
  if (m) details.chimneys = numberFromMatch(m);
  m = msg.match(/\b(\d+)\s*(?:skylight|skylights)\b/);
  if (m) details.skylights = numberFromMatch(m);
  m = msg.match(/\b(\d+)\s*(?:pipe boot|pipe boots|boots|pipes|penetrations|vents)\b/);
  if (m) details.pipeBoots = numberFromMatch(m);

  m = msg.match(/\b(\d+)\s*(?:sheet|sheets)\b/);
  if (m && /deck|decking|plywood|osb|sheathing/.test(msg)) details.deckingSheets = numberFromMatch(m);
  m = msg.match(/\b(\d{2,5})\s*(?:sf|sqft|sq ft|square feet)\s*(?:decking|deck|sheathing)\b/);
  if (m) details.deckingSqFt = numberFromMatch(m);
  if (/\bbad decking|soft decking|rotten decking|decking is bad|bad deck|soft spots|delaminated\b/.test(msg)) {
    details.deckingCondition = "suspect or damaged";
  }

  if (/\bdumpster|dump access|driveway access|haul off|disposal\b/.test(msg)) notes.push(text);

  const DUMPSTER_NEGATION_RE =
    /\b(?:no|not|don't|won't|without|skip)\b[^.]{0,20}\bdumpster\b|\bcustomer\s+(?:has|is\s+supplying|providing|bringing)\s+(?:a\s+|the\s+|their\s+own\s+)?dumpster\b|\balready\s+has\s+a\s+dumpster\b/;
  if (DUMPSTER_NEGATION_RE.test(msg)) details.dumpsterRequested = false;

  if (/\bpermit|permits\b/.test(msg)) details.permitRequired = !/no permit|not required/.test(msg);
  if (/\bridge vent|box vents|ventilation|intake|exhaust\b/.test(msg)) details.ventilation = text;
  if (/\bflashing|step flashing|counter flashing|apron flashing|wall flashing\b/.test(msg)) details.flashingScope = text;

  const customerName = extractCustomerNameLoose(text);
  if (customerName) details.customerName = customerName;
  const customerAddress = extractCustomerAddress(text);
  if (customerAddress) details.customerAddress = customerAddress;

  if (notes.length) details.notes = notes;
  return details;
}

function mergeJobDetails(job, details) {
  const updatedFields = [];
  for (const [key, value] of Object.entries(details || {})) {
    if (value === null || value === undefined || value === "") continue;
    if (key === "notes") {
      job.notes = Array.isArray(job.notes) ? job.notes : [];
      for (const note of value) job.notes.push(note);
      updatedFields.push("notes");
      continue;
    }
    job[key] = value;
    updatedFields.push(key);
  }
  return updatedFields;
}

// -----------------------------------------------------------------------------
// Intent classification — retained ONLY as the fallback path's routing logic
// and for lightweight logging/analytics.
// -----------------------------------------------------------------------------

const CORE_MEASUREMENT_FIELDS = ["squares", "pitch", "stories", "tearOffLayers", "material"];

function hasCoreMeasurementUpdate(details) {
  if (!details) return false;
  return CORE_MEASUREMENT_FIELDS.some(
    (field) => details[field] !== undefined && details[field] !== null && details[field] !== ""
  );
}

const EXPLAIN_TRIGGER_RE =
  /\b(why|expensive|so high|too high|too much|high|cost driver|breakdown|explain|difference|delta|changed|change|went up|went down|different)\b/;

function classifyIntent(text, details) {
  const msg = lower(text);

  if (/\b(reset|start over|new roof|new estimate|clear this)\b/.test(msg)) return "reset_estimate";
  if (/\b(help|what can you do)\b/.test(msg)) return "help";
  // *** FIX: narrowed from a bare \b(homeowner|customer|...)\b match, which
  // incorrectly fired on ANY message merely containing the word "customer" -
  // including completely normal job-info messages like "...architectural
  // shingles Kristy Smith customer 313 Johnsborough drive" (this is exactly
  // how estimators label whose job a set of measurements belongs to, so the
  // word "customer" appears constantly in totally unrelated messages). Now
  // requires an actual explain/tell/say phrase alongside "homeowner" (or the
  // explicit phrase "tell the customer" / "say to the customer"), so a bare
  // customer-info message no longer gets misrouted into homeowner-facing
  // wording help. ***
  if (/\bhomeowner\b/.test(msg) && /\b(explain|tell|say|word it|wording)\b/.test(msg)) return "homeowner_response_help";
  if (/\b(explain to|tell)\s+(the\s+)?customer\b/.test(msg) || /\bsay to (the\s+)?customer\b/.test(msg)) return "homeowner_response_help";
  if (EXPLAIN_TRIGGER_RE.test(msg)) return "explain_price";
  if (/\b(quote|estimate|price|range|rough number|how much|total|cost)\b/.test(msg)) return "request_estimate";
  if (/\b(cheaper|lower|save money|value engineer|reduce)\b/.test(msg)) return "lower_price";
  if (/\b(competitor|another roofer|other bid|cheaper bid|match)\b/.test(msg)) return "competitor_comparison";
  if (/\b(missing|need from me|what else|what do you need)\b/.test(msg)) return "missing_info";
  if (/\b(check before i leave|field checklist|look for|inspect|before leaving|driveway)\b/.test(msg)) return "field_checklist";
  if (/\b(insurance|supplement|claim|adjuster|storm|hail|wind)\b/.test(msg)) return "insurance_or_supplement";
  if (hasCoreMeasurementUpdate(details)) return "provide_measurement";
  if (/\b(decking|deck|sheathing|plywood|osb|sheets)\b/.test(msg)) return "decking";
  if (/\b(chimney|flashing|skylight|pipe boot|penetration|valley|ventilation|ridge vent)\b/.test(msg)) return "scope_detail";
  if (details && Object.keys(details).length > 0) return "provide_measurement";
  if (msg.length < 8) return "unclear";

  return "general_roofing_question";
}

// -----------------------------------------------------------------------------
// Roofing estimate logic — deterministic, unchanged.
// -----------------------------------------------------------------------------

const REQUIRED_FIELDS = ["squares", "pitch", "stories", "tearOffLayers", "material"];

function missingRequiredFields(job) {
  return REQUIRED_FIELDS.filter((field) => job[field] === null || job[field] === undefined || job[field] === "");
}

function formatFieldName(field) {
  const names = {
    squares: "squares",
    pitch: "pitch",
    stories: "one-story or two-story access",
    tearOffLayers: "tear-off layer count",
    material: "shingle or material choice"
  };
  return names[field] || field;
}

function knownJobBullets(job) {
  const bullets = [];
  if (job.squares) bullets.push(`${job.squares} squares`);
  if (job.pitch) bullets.push(`${job.pitch} pitch`);
  if (job.stories) bullets.push(`${job.stories}-story access`);
  if (job.tearOffLayers !== null && job.tearOffLayers !== undefined) {
    bullets.push(`${job.tearOffLayers} tear-off layer${job.tearOffLayers === 1 ? "" : "s"}`);
  }
  if (job.material) bullets.push(job.material);
  if (job.complexity) bullets.push(`${job.complexity} roof complexity`);
  if (job.chimneys !== null && job.chimneys !== undefined) bullets.push(`${job.chimneys} chimney${job.chimneys === 1 ? "" : "s"}`);
  if (job.skylights !== null && job.skylights !== undefined) bullets.push(`${job.skylights} skylight${job.skylights === 1 ? "" : "s"}`);
  if (job.pipeBoots !== null && job.pipeBoots !== undefined) {
    bullets.push(`${job.pipeBoots} pipe boot/penetration${job.pipeBoots === 1 ? "" : "s"}`);
  }
  if (job.deckingSheets) bullets.push(`${job.deckingSheets} decking sheet${job.deckingSheets === 1 ? "" : "s"} as an adder`);
  if (job.deckingCondition) bullets.push(`decking condition: ${job.deckingCondition}`);
  if (job.dumpsterRequested === false) bullets.push("no dumpster needed - customer/estimator supplying their own (disposal fee removed)");
  return bullets;
}

function parsePitchNumber(pitch) {
  const m = String(pitch || "").match(/(\d{1,2})/);
  return m ? Number(m[1]) : null;
}

function calculateDeckingAdder(job) {
  const deckSheetAdder = Number(process.env.ROOFING_DECK_SHEET_ADDER || 95);
  let deckingLow = 0;
  let deckingHigh = 0;
  if (job.deckingSheets) {
    deckingLow = Number(job.deckingSheets) * deckSheetAdder;
    deckingHigh = Number(job.deckingSheets) * Math.round(deckSheetAdder * 1.25);
  }
  return { deckingLow, deckingHigh };
}

function calculateDumpsterFee(job) {
  const included = job.dumpsterRequested !== false;
  if (!included) return { dumpsterFee: 0, dumpsterIncluded: false };
  const configuredFee = Number(process.env.ROOFING_DUMPSTER_FEE || 450);
  return { dumpsterFee: configuredFee, dumpsterIncluded: true };
}

// *** FIX: roofingPricing.js's calculateRoofEstimate() returns a SINGLE
// POINT PRICE ("price"), plus a flat "breakdown" object with its own field
// names (materials, labor, pitch_surcharge, total_cost, gross_margin,
// gross_profit, price_per_square, etc) - NOT the {low, high, totalLow,
// totalHigh, breakdown:{materials_and_labor,...}} shape that
// persistToDatabase(), the template reply builders (estimateReply,
// explainPriceReply, deckingReply, homeownerHelpReply), and
// promptBuilder.js's buildDataBlock() all expect and were built against.
//
// That mismatch was NEVER caught before now because it was previously
// masked by the lib/db.js shadowing bug: persistToDatabase's
// "estimatorContext" check failed first (db module had no saveEstimate),
// so the missing-totalLow/totalHigh problem never got far enough to
// surface on its own. Once the db shadowing was fixed, this became the
// very next blocker - the company-pricing-profile path was ALWAYS
// producing an estimate object with no low/high, on every real customer
// job priced with an actual company profile (as opposed to the generic
// demo/fallback path), silently breaking both persistence AND the SMS
// reply text (which would show $0 or blank ranges) the entire time.
//
// This function now normalizes the real engine's single-price result into
// the SAME canonical shape fallbackEstimate() below already produces, so
// every downstream consumer (persistToDatabase, reply builders,
// promptBuilder) keeps working unchanged and does not need to special-case
// two different estimate shapes.
//
// *** DESIGN DECISION FLAGGED FOR CONFIRMATION ***
// roofingPricing.js computes one exact number, not a range. Per prior
// direction that estimates should present as a range (not a single flat
// number), this wraps that point price in a symmetric +/-6% spread
// (configurable via ROOFING_PROFILE_RANGE_SPREAD) purely to stay
// consistent with the rest of the app. This is an assumption on my part,
// not a fact taken from your pricing engine - confirm the spread
// percentage is right for how tight you want quoted ranges to be, and let
// me know if you'd rather show the exact single price with no synthetic
// range instead.
function calculateFromCompanyPricing(job, estimatorContext) {
  if (!estimatorContext || !estimatorContext.pricing) return null;
  if (!pricingModule || typeof pricingModule.calculateRoofEstimate !== "function") return null;

  try {
    const mappedJob = mapJobForPricingEngine(job);
    const shingle = resolveShingle(estimatorContext, job.material);
    const result = pricingModule.calculateRoofEstimate(mappedJob, estimatorContext.pricing, shingle);
    if (!result || result.error) return null;

    // Already in canonical shape (has low/high) - some future version of
    // roofingPricing.js might return a range directly. Pass through with
    // only the metadata fields added, same as before.
    if (result.low !== undefined && result.high !== undefined) {
      return {
        ...result,
        source: "company-pricing-profile",
        companyName: estimatorContext.companyName,
        shingleUsed: shingle ? shingle.name : null
      };
    }

    // Real observed shape: a single point "price", plus a flat breakdown
    // object. Normalize into the canonical {low, high, totalLow, totalHigh,
    // breakdown:{...}} shape used everywhere else in this file and in
    // promptBuilder.js.
    if (result.price !== undefined) {
      // *** CORRECTED: after reviewing the actual lib/roofingPricing.js
      // source, it already defines its own confidence-weighted range logic
      // (estimateConfidence + estimateRange: High=6%, Medium=10%, Low=15%
      // variance, based on how many optional detail fields - chimneys,
      // penetrations, ridge/eave LF, etc - were actually provided). Those
      // two functions are not currently exported from that file (only
      // calculateRoofEstimate, formatRoofingReply, and money are), so this
      // reproduces the IDENTICAL rule here rather than guessing a flat
      // percentage as the previous version of this fix did. This gives a
      // tighter range when the estimator provided more detail (chimneys,
      // valleys, ridge/eave LF, etc), and a wider one when only the bare
      // required fields were given - matching your own file's intent
      // exactly instead of a one-size-fits-all guess.
      //
      // NOTE: if you'd rather avoid this duplicated logic living in two
      // files, the cleaner long-term fix is adding
      // `estimateConfidence, estimateRange` to roofingPricing.js's
      // module.exports (currently only calculateRoofEstimate,
      // formatRoofingReply, money are exported) - then this block can call
      // pricingModule.estimateConfidence/estimateRange directly instead of
      // reimplementing them. Flagging this as a recommendation, not doing
      // it automatically, since it means touching your pricing file.
      const price = Number(result.price);
      const inputs = result.inputs || {};
      let confidenceScore = 0;
      if (result.squares) confidenceScore++;
      if (inputs.pitch) confidenceScore++;
      if (inputs.stories) confidenceScore++;
      if (inputs.layers !== undefined) confidenceScore++;
      if (inputs.chimneys) confidenceScore++;
      if (inputs.penetrations) confidenceScore++;
      if (inputs.ridge_lf) confidenceScore++;
      if (inputs.eave_lf) confidenceScore++;
      let confidence = "Low";
      if (confidenceScore >= 4) confidence = "High";
      else if (confidenceScore >= 3) confidence = "Medium";
      let spreadPct = 0.15;
      if (confidence === "High") spreadPct = 0.06;
      else if (confidence === "Medium") spreadPct = 0.1;

      const low = Math.round((price * (1 - spreadPct)) / 100) * 100;
      const high = Math.round((price * (1 + spreadPct)) / 100) * 100;

      const b = result.breakdown || {};
      const dumpsterFeeApplied = b.dumpster != null ? Number(b.dumpster) : null;
      const dumpsterIncluded = result.flags ? Boolean(result.flags.dumpster_included) : dumpsterFeeApplied != null && dumpsterFeeApplied > 0;

      return {
        low,
        high,
        totalLow: low,
        totalHigh: high,
        // roofingPricing.js does not appear to compute a separate decking
        // adder anywhere in its output (no deck-related field observed) -
        // left at 0 rather than guessed. If your pricing engine DOES
        // support a decking adder under a different field name, tell me
        // what it's called and I'll wire it in here instead of assuming 0.
        deckingLow: 0,
        deckingHigh: 0,
        dumpsterIncluded,
        dumpsterFeeApplied,
        detailAdders: [],
        confidence,
        pricePerSquare: b.price_per_square != null ? b.price_per_square : null,
        grossMargin: b.gross_margin != null ? b.gross_margin : null,
        priceFlags: result.flags || null,
        source: "company-pricing-profile",
        companyName: estimatorContext.companyName,
        shingleUsed: shingle ? shingle.name : null,
        breakdown: {
          materials: b.materials != null ? b.materials : undefined,
          labor: b.labor != null ? b.labor : undefined,
          tearoff: b.tearoff != null ? b.tearoff : undefined,
          ridge: b.ridge != null ? b.ridge : undefined,
          eave: b.eave != null ? b.eave : undefined,
          valley: b.valley != null ? b.valley : undefined,
          accessories: b.accessories != null ? b.accessories : undefined,
          dumpster: dumpsterFeeApplied,
          pitch_surcharge: b.pitch_surcharge != null ? b.pitch_surcharge : undefined,
          two_story_surcharge: b.two_story_surcharge != null ? b.two_story_surcharge : undefined
        },
        // Full untouched original result, preserved in case anything needs
        // to inspect fields not mapped above (e.g. inputs, total_cost,
        // gross_profit).
        rawEngineResult: result
      };
    }

    // Unrecognized shape entirely - do not silently pass through something
    // that will break persistence/reply-building again. Log it loudly and
    // fall back to the generic estimator instead of guessing further.
    console.error(
      "[BidBuddy SMS] calculateRoofEstimate() returned an unrecognized shape (no low/high, no price). Falling back to generic pricing.",
      JSON.stringify(result)
    );
    return null;
  } catch (err) {
    console.error("[BidBuddy SMS] calculateFromCompanyPricing threw an error - falling back to generic pricing.", err);
    return null;
  }
}

function fallbackEstimate(job) {
  const basePerSquare = Number(process.env.ROOFING_BASE_PER_SQUARE || 475);
  const designerPerSquare = Number(process.env.ROOFING_DESIGNER_PER_SQUARE || 725);
  const metalPerSquare = Number(process.env.ROOFING_METAL_PER_SQUARE || 950);
  const tilePerSquare = Number(process.env.ROOFING_TILE_PER_SQUARE || 1100);
  const slatePerSquare = Number(process.env.ROOFING_SLATE_PER_SQUARE || 1400);
  const tearOffPerSquare = Number(process.env.ROOFING_TEAROFF_PER_SQUARE || 75);
  const secondStoryPerSquare = Number(process.env.ROOFING_SECOND_STORY_PER_SQUARE || 45);

  const squares = Number(job.squares || 0);
  let perSquare = basePerSquare;

  if (/3-tab/.test(job.material || "")) perSquare = Math.max(basePerSquare - 40, 350);
  if (/designer/.test(job.material || "")) perSquare = designerPerSquare;
  if (/metal/.test(job.material || "")) perSquare = metalPerSquare;
  if (/tile/.test(job.material || "")) perSquare = tilePerSquare;
  if (/slate/.test(job.material || "")) perSquare = slatePerSquare;

  const pitchNum = parsePitchNumber(job.pitch);
  let pitchMultiplier = 1;
  if (pitchNum >= 7 && pitchNum <= 9) pitchMultiplier = 1.08;
  if (pitchNum >= 10 && pitchNum <= 12) pitchMultiplier = 1.18;
  if (pitchNum > 12) pitchMultiplier = 1.3;

  let complexityMultiplier = 1;
  if (job.complexity === "moderate") complexityMultiplier = 1.05;
  if (job.complexity === "complex") complexityMultiplier = 1.12;

  const baseInstall = squares * perSquare;
  const tearOffCost = squares * tearOffPerSquare * Number(job.tearOffLayers || 0);
  const secondStoryCost = Number(job.stories || 1) >= 2 ? squares * secondStoryPerSquare : 0;
  let structuralSubtotal = baseInstall + tearOffCost + secondStoryCost;
  structuralSubtotal *= pitchMultiplier;
  structuralSubtotal *= complexityMultiplier;

  const valleyPerLf = Number(process.env.ROOFING_VALLEY_PER_LF || 12);
  const detailAdders = [];
  if (job.chimneys) detailAdders.push({ name: "chimney flashing allowance", amount: Number(job.chimneys) * 250 });
  if (job.skylights) detailAdders.push({ name: "skylight flashing allowance", amount: Number(job.skylights) * 275 });
  if (job.pipeBoots) detailAdders.push({ name: "pipe boot allowance", amount: Number(job.pipeBoots) * 65 });
  if (job.valleyLf) detailAdders.push({ name: "valley flashing", amount: Number(job.valleyLf) * valleyPerLf });
  const accessoriesCost = detailAdders.reduce((sum, a) => sum + a.amount, 0);

  const { dumpsterFee, dumpsterIncluded } = calculateDumpsterFee(job);

  const subtotal = structuralSubtotal + accessoriesCost + dumpsterFee;

  const baseLow = Math.round((subtotal * 0.94) / 100) * 100;
  const baseHigh = Math.round((subtotal * 1.08) / 100) * 100;

  const { deckingLow, deckingHigh } = calculateDeckingAdder(job);

  return {
    low: baseLow,
    high: baseHigh,
    deckingLow,
    deckingHigh,
    dumpsterIncluded,
    dumpsterFeeApplied: dumpsterFee,
    totalLow: baseLow + deckingLow,
    totalHigh: baseHigh + deckingHigh,
    detailAdders,
    source: "fallback",
    breakdown: {
      materials_and_labor: Math.round(baseInstall * pitchMultiplier * complexityMultiplier),
      tearoff: Math.round(tearOffCost * pitchMultiplier * complexityMultiplier),
      ridge: 0,
      eave: 0,
      accessories: Math.round(accessoriesCost),
      dumpster: Math.round(dumpsterFee),
      second_story: Math.round(secondStoryCost * pitchMultiplier * complexityMultiplier),
      pitch_multiplier: pitchMultiplier,
      complexity_multiplier: complexityMultiplier
    }
  };
}

function calculateEstimate(job, estimatorContext) {
  const fromCompany = calculateFromCompanyPricing(job, estimatorContext);
  if (fromCompany) return fromCompany;
  return fallbackEstimate(job);
}

function tryCalculateEstimate(job, estimatorContext) {
  if (missingRequiredFields(job).length) return null;
  return calculateEstimate(job, estimatorContext);
}

function dollars(n) {
  if (n === null || n === undefined || Number.isNaN(Number(n))) return "$0";
  return `$${Math.round(Number(n)).toLocaleString("en-US")}`;
}

// -----------------------------------------------------------------------------
// *** THE FIX: persist the estimate + customer name/address to the database ***
// Now with explicit, always-on diagnostic logging on every path.
// -----------------------------------------------------------------------------

function persistToDatabase({ estimatorContext, job, estimate, thread, phoneKey }) {
  if (!estimatorContext || !dbModule || typeof dbModule.saveEstimate !== "function") {
    console.log(
      "[BidBuddy SMS] persistToDatabase SKIPPED - no save attempted.",
      JSON.stringify({
        phoneKey,
        hasEstimatorContext: Boolean(estimatorContext),
        hasDbModule: Boolean(dbModule),
        hasSaveEstimateFn: Boolean(dbModule && typeof dbModule.saveEstimate === "function")
      })
    );
    return;
  }
  if (!estimate) {
    console.log("[BidBuddy SMS] persistToDatabase SKIPPED - no computed estimate object was passed in.", JSON.stringify({ phoneKey }));
    return;
  }

  const totalLow = estimate.totalLow ?? estimate.low;
  const totalHigh = estimate.totalHigh ?? estimate.high;
  if (totalLow == null || totalHigh == null) {
    console.log("[BidBuddy SMS] persistToDatabase SKIPPED - estimate had no totalLow/totalHigh.", JSON.stringify({ phoneKey, estimate }));
    return;
  }

  const estimateAmount = Math.round((Number(totalLow) + Number(totalHigh)) / 2);

  const payload = {
    company_id: estimatorContext.companyId,
    created_by_user_id: estimatorContext.user ? estimatorContext.user.id : null,
    customer_name: job.customerName || null,
    job_address: job.customerAddress || null,
    squares: job.squares || null,
    estimate_amount: estimateAmount,
    estimate_json: estimate,
    source: "sms"
  };

  try {
    if (thread.dbEstimateId && typeof dbModule.updateEstimate === "function") {
      const updated = dbModule.updateEstimate(thread.dbEstimateId, estimatorContext.companyId, payload);
      if (!updated) {
        thread.dbEstimateId = dbModule.saveEstimate(payload);
        console.log(
          `[BidBuddy SMS] persistToDatabase: UPDATE targeted a missing row - self-healed with a fresh INSERT. New row id=${thread.dbEstimateId}.`,
          JSON.stringify({ phoneKey, company_id: payload.company_id, customer_name: payload.customer_name, job_address: payload.job_address })
        );
      } else {
        console.log(
          `[BidBuddy SMS] persistToDatabase: UPDATE succeeded on row id=${thread.dbEstimateId}.`,
          JSON.stringify({ phoneKey, company_id: payload.company_id, customer_name: payload.customer_name, job_address: payload.job_address })
        );
      }
      return;
    }
    thread.dbEstimateId = dbModule.saveEstimate(payload);
    console.log(
      `[BidBuddy SMS] persistToDatabase: INSERT succeeded. New row id=${thread.dbEstimateId}.`,
      JSON.stringify({ phoneKey, company_id: payload.company_id, customer_name: payload.customer_name, job_address: payload.job_address })
    );
  } catch (err) {
    console.error("[BidBuddy SMS] persistToDatabase FAILED (exception thrown by dbModule).", JSON.stringify({ phoneKey, payload }), err);
  }
}

// -----------------------------------------------------------------------------
// *** PART OF FIX #1: cross-job clarification guardrail helpers ***
// -----------------------------------------------------------------------------

function describeThreadForClarification(thread, index) {
  const bits = [];
  if (thread.job.squares) bits.push(`${thread.job.squares} squares`);
  if (thread.job.pitch) bits.push(`${thread.job.pitch} pitch`);
  if (thread.job.material) bits.push(thread.job.material);
  const desc = bits.length ? bits.join(", ") : "a job with no details yet";
  return `${index + 1}) ${desc}`;
}

function buildClarificationReply(candidates) {
  const lines = [
    "I've got more than one job going on this number without a name attached yet. Which one is this for?",
    ""
  ];
  candidates.forEach((t, i) => lines.push(describeThreadForClarification(t, i)));
  lines.push("");
  lines.push("Reply with the number (1, 2, ...) or the squares count and I'll attach it.");
  return lines.join("\n");
}

function resolvePendingAssignment(bucket, cleaned) {
  const pending = bucket.pendingAssignment;
  if (!pending) return null;
  const msg = lower(cleaned);
  const candidateIds = pending.candidateThreadIds || [];
  const candidates = candidateIds.map((id) => bucket.threads[id]).filter(Boolean);
  if (!candidates.length) return null;

  const ORDINAL_WORDS = [
    ["first", "1st"],
    ["second", "2nd"],
    ["third", "3rd"],
    ["fourth", "4th"],
    ["fifth", "5th"]
  ];

  const numMatch = msg.match(/\b(\d+)\b/);
  if (numMatch) {
    const n = Number(numMatch[1]);
    if (n >= 1 && n <= candidates.length) return candidates[n - 1];
    const bySquares = candidates.find((t) => Number(t.job.squares) === n);
    if (bySquares) return bySquares;
  }

  for (let i = 0; i < ORDINAL_WORDS.length && i < candidates.length; i++) {
    if (ORDINAL_WORDS[i].some((w) => msg.includes(w))) return candidates[i];
  }
  if (/\blast\b/.test(msg)) return candidates[candidates.length - 1];

  return null;
}

// -----------------------------------------------------------------------------
// Template-based reply builders — RETAINED AS FALLBACK ONLY.
// -----------------------------------------------------------------------------

function smsJoin(lines) {
  return lines
    .filter((line) => line !== null && line !== undefined && String(line).trim() !== "")
    .join("\n");
}

function bulletList(items) {
  return items.filter(Boolean).map((item) => `- ${item}`).join("\n");
}

function pricingSourceNote(estimate) {
  if (!estimate) return "";
  if (estimate.source === "company-pricing-profile") {
    return `(using ${estimate.companyName || "your"} company pricing${estimate.shingleUsed ? ", " + estimate.shingleUsed : ""})`;
  }
  return "(using generic default pricing - no company profile matched this number)";
}

function missingInfoReply(job) {
  const known = knownJobBullets(job);
  const missing = missingRequiredFields(job).map(formatFieldName);
  if (!missing.length) {
    return smsJoin([
      "I have the required items for a rough roof number.",
      "",
      "Current basis:",
      bulletList(known),
      "",
      "Helpful extras if you have them: valleys, chimneys, skylights, pipe boots, decking condition, dump access, and any flashing or ventilation changes."
    ]);
  }
  return smsJoin([
    known.length ? "Here's what I have so far:" : "I can build the roof estimate, but I need the basics first.",
    known.length ? bulletList(known) : "",
    "",
    "Still need:",
    bulletList(missing),
    "",
    "Send what you know next and I'll keep building it."
  ]);
}

function measurementReply(job, updatedFields) {
  const missing = missingRequiredFields(job).map(formatFieldName);
  const known = knownJobBullets(job);
  if (!updatedFields.length) {
    return "I'm not totally sure what to do with that yet. Send it like: 30 squares, 8/12 pitch, two story, one layer tear-off, architectural shingles.";
  }
  if (missing.length) {
    return smsJoin([
      "Got it. I updated the roof details.",
      "",
      "Current basis:",
      bulletList(known),
      "",
      "Still need to tighten the number:",
      bulletList(missing)
    ]);
  }
  return smsJoin([
    "Got it. I have enough to rough this in now.",
    "",
    "Current basis:",
    bulletList(known),
    "",
    "Send 'estimate' and I'll give you the range with assumptions and adders."
  ]);
}

function estimateReply(job, conversation) {
  const missing = missingRequiredFields(job).map(formatFieldName);
  const known = knownJobBullets(job);
  if (missing.length) {
    return smsJoin([
      "I can rough it in, but I don't want to fake a number with key items missing.",
      "",
      known.length ? "What I have:" : "",
      known.length ? bulletList(known) : "",
      "",
      "Still need:",
      bulletList(missing),
      "",
      "Send those and I'll give you a tighter range."
    ]);
  }
  const estimate = calculateEstimate(job, conversation.estimatorContext);
  conversation.lastEstimate = { ...estimate, createdAt: new Date().toISOString() };
  const hasDeckingAdder = estimate.deckingLow || estimate.deckingHigh;
  const totalLine = hasDeckingAdder
    ? `Updated rough total with decking adder: ${dollars(estimate.totalLow)} to ${dollars(estimate.totalHigh)}`
    : "";

  let customerNudge = "";
  if (!job.customerName && conversation && !conversation.askedForCustomerInfo) {
    customerNudge = job.customerAddress
      ? "Who's this for? Reply with 'customer [name]' and I'll attach it to this estimate."
      : "Who's this for, and do you have the property address? Reply with 'customer [name], [address]' and I'll save it under that job.";
    if (conversation) conversation.askedForCustomerInfo = true;
  }

  return smsJoin([
    "Here's the rough roof replacement range based on the field info:",
    "",
    "Estimate basis:",
    bulletList(known),
    "",
    `Base roof range: ${dollars(estimate.low)} to ${dollars(estimate.high)}`,
    hasDeckingAdder ? `Decking adder: ${dollars(estimate.deckingLow)} to ${dollars(estimate.deckingHigh)}` : "",
    estimate.dumpsterIncluded
      ? `Dumpster/disposal: ${dollars(estimate.dumpsterFeeApplied || 0)} included in the base range above`
      : "Dumpster/disposal: not included - customer/estimator supplying their own",
    totalLine,
    "",
    "Included assumptions:",
    bulletList([
      "normal tear-off/disposal for the layers provided",
      "standard underlayment, starter, drip edge, and ridge cap",
      "standard labor adjustment for pitch and access",
      "normal pipe boot/flashing allowance unless noted otherwise"
    ]),
    "",
    "Not included unless confirmed:",
    bulletList([
      "deck replacement beyond listed sheets",
      "structural repairs",
      "chimney flashing rebuilds",
      "skylight replacement",
      "permit or code-driven changes"
    ]),
    "",
    "If you see valleys, chimneys, skylights, or bad decking, send those next and I'll adjust it.",
    "",
    pricingSourceNote(estimate),
    customerNudge ? "" : "",
    customerNudge
  ]);
}

function explainPriceReply(job, conversation) {
  const known = knownJobBullets(job);
  const drivers = [];
  if (job.squares) drivers.push(`${job.squares} squares drives the material, labor, and disposal volume.`);
  if (job.pitch) drivers.push(`${job.pitch} pitch affects labor speed, setup, and safety.`);
  if (Number(job.stories || 1) >= 2) drivers.push("Two-story access usually adds labor and setup time.");
  if (Number(job.tearOffLayers || 0) > 0) {
    drivers.push(`${job.tearOffLayers} tear-off layer${job.tearOffLayers === 1 ? "" : "s"} adds removal and disposal.`);
  }
  if (job.material) drivers.push(`${job.material} controls a big part of the material cost.`);
  if (job.complexity === "complex") drivers.push("The roof is marked complex, so waste and labor risk are higher.");
  if (job.deckingSheets || job.deckingCondition) drivers.push("Decking should stay separate because final sheet count can change after tear-off.");
  if (!drivers.length) {
    drivers.push("The biggest roof price drivers are squares, pitch, stories/access, tear-off layers, material choice, disposal, flashing details, and decking condition.");
  }

  const missing = missingRequiredFields(job);
  const hasEstimate = conversation && conversation.lastEstimate && !missing.length;

  if (hasEstimate) {
    const current = calculateEstimate(job, conversation.estimatorContext);
    const prior = conversation.lastEstimate;
    const priorLow = Number(prior.totalLow ?? prior.low ?? 0);
    const priorHigh = Number(prior.totalHigh ?? prior.high ?? 0);
    const currentLow = Number(current.totalLow ?? current.low ?? 0);
    const currentHigh = Number(current.totalHigh ?? current.high ?? 0);
    const changed = priorLow !== currentLow || priorHigh !== currentHigh;
    if (changed) {
      return smsJoin([
        "Here's the difference:",
        "",
        `Previous range: ${dollars(priorLow)} to ${dollars(priorHigh)}`,
        `Current range: ${dollars(currentLow)} to ${dollars(currentHigh)}`,
        "",
        "On this roof:",
        bulletList(drivers),
        "",
        "That shift is coming from whatever details were added or changed since the last estimate. Send 'estimate' again any time you want the current number restated."
      ]);
    }
    return smsJoin([
      "The number hasn't actually changed since the last estimate I gave you.",
      "",
      `Current range: ${dollars(currentLow)} to ${dollars(currentHigh)}`,
      "",
      "If you were expecting a different number, let me know what changed on the job and I'll rerun it.",
      "",
      "Main drivers on this roof:",
      bulletList(drivers)
    ]);
  }

  return smsJoin([
    "The number is mainly being driven by scope, labor, and risk, not just shingles.",
    "",
    known.length ? "On this roof:" : "Typical drivers:",
    bulletList(drivers),
    "",
    "I'd present it as a rough replacement range until decking, flashing, and hidden conditions are confirmed."
  ]);
}

function lowerPriceReply() {
  return smsJoin([
    "Maybe, but I wouldn't cut waterproofing items just to make the number look better.",
    "",
    "Safer places to review:",
    bulletList([
      "shingle product level",
      "whether ventilation changes are included",
      "dump/disposal assumptions",
      "whether decking is separate instead of buried in the base",
      "scope differences versus another bid"
    ]),
    "",
    "I would not remove drip edge, starter, underlayment, flashing, or required ice/water protection just to lower the price."
  ]);
}

function deckingReply(job, conversation) {
  const lines = [
    "I'd keep decking separate from the base roof number unless the sheet count is already confirmed.",
    "",
    "Best structure:",
    bulletList([
      "base roof replacement covers normal tear-off and install",
      "decking is listed as a per-sheet or allowance adder",
      "final decking quantity is confirmed after tear-off"
    ])
  ];
  if (job.deckingSheets) {
    const estimate = calculateEstimate(job, conversation.estimatorContext);
    lines.push("");
    lines.push(`I have ${job.deckingSheets} decking sheet${job.deckingSheets === 1 ? "" : "s"} noted as an adder.`);
    lines.push(`Current decking adder: ${dollars(estimate.deckingLow)} to ${dollars(estimate.deckingHigh)}`);
  } else if (job.deckingCondition) {
    lines.push("");
    lines.push("You mentioned suspect decking. Send the number of sheets if you have it. If not, I'd call it out as a per-sheet adder after tear-off.");
  } else {
    lines.push("");
    lines.push("Send the number of sheets, square footage, or a note like 'soft decking around eaves' and I'll treat it as a separate adder.");
  }
  return smsJoin(lines);
}

function scopeDetailReply(job) {
  return smsJoin([
    "Good callout. Details like chimneys, skylights, pipe boots, valleys, ventilation, and flashing can move the number.",
    "",
    "What I have noted:",
    bulletList(knownJobBullets(job).length ? knownJobBullets(job) : ["no detailed roof accessories captured yet"]),
    "",
    "If you can, send counts like: 2 chimneys, 1 skylight, 6 pipe boots, 40 LF valley. I'll adjust the estimate around those details."
  ]);
}

function homeownerHelpReply(job, conversation) {
  const hasFullEstimate = !missingRequiredFields(job).length;
  if (!hasFullEstimate) {
    return smsJoin([
      "Here's a safe way to say it before the number is fully tightened:",
      "",
      "'I'm still confirming a few roof details, but the final price will depend on the roof size, pitch, tear-off, access, material choice, and any hidden decking or flashing issues we find.'",
      "",
      "Once you send the missing basics, I'll help you word the actual range."
    ]);
  }
  const range = calculateEstimate(job, conversation.estimatorContext);
  return smsJoin([
    "Here's how I'd explain it to the homeowner:",
    "",
    `Based on what we can see today, this roof is likely in the ${dollars(range.totalLow)} to ${dollars(range.totalHigh)} range. That includes the roof replacement, tear-off, disposal, standard accessories, and labor for the pitch and access. The final number can change if we uncover bad decking, hidden damage, or flashing issues after tear-off.`,
    "",
    "That gives them a real number without locking you into hidden conditions."
  ]);
}

function competitorReply() {
  return smsJoin([
    "I'd compare scope, not just the total price.",
    "",
    "Ask if the cheaper bid includes:",
    bulletList([
      "tear-off and disposal",
      "drip edge, starter, underlayment, and ridge cap",
      "ice/water where required",
      "flashing details",
      "decking adders",
      "permit assumptions",
      "ventilation changes",
      "warranty terms"
    ]),
    "",
    "A cheaper bid may be fine, but only if the scope is actually the same."
  ]);
}

function fieldChecklistReply() {
  return smsJoin([
    "Before you leave, I'd check these items:",
    "",
    bulletList([
      "confirm squares or roof measurement",
      "confirm pitch",
      "confirm one-story or two-story access",
      "confirm tear-off layers",
      "note shingle/material choice",
      "count chimneys, skylights, pipe boots, and valleys",
      "look for soft decking, waves, or leak areas",
      "confirm dump access and driveway limitations",
      "note flashing and ventilation concerns"
    ]),
    "",
    "Those are the items most likely to change the rough number after you leave the property."
  ]);
}

function insuranceReply() {
  return smsJoin([
    "For insurance or supplement work, I'd keep the wording scope-based and factual.",
    "",
    "Use language like:",
    "'Estimate includes roof replacement scope observed in the field. Final scope may change based on tear-off findings, decking condition, flashing requirements, and code or permit requirements.'",
    "",
    "I wouldn't promise coverage or approval. Keep it to observed damage, measured scope, and clearly listed assumptions."
  ]);
}

function helpReply() {
  return smsJoin([
    "I can help you build and explain a rough roof estimate from the field.",
    "",
    "Send details like:",
    bulletList([
      "30 squares",
      "8/12 pitch",
      "two story",
      "one layer tear-off",
      "architectural shingles",
      "2 chimneys, 1 skylight, 6 pipe boots",
      "add 10 sheets decking"
    ]),
    "",
    "You can also ask: estimate, what am I missing, why so high, explain to homeowner, competitor is cheaper, or field checklist."
  ]);
}

function generalRoofingReply(job) {
  return smsJoin([
    "I can help with that from an estimating angle.",
    "",
    "For this roof, I'm focused on the details that affect price: squares, pitch, access, tear-off, material, decking, flashing, ventilation, and roof complexity.",
    "",
    missingRequiredFields(job).length
      ? "If you want a number, send the missing basics and I'll tighten the range."
      : "If you want, send 'estimate' and I'll price the current scope."
  ]);
}

function unclearReply(job) {
  return smsJoin([
    "I may need that one a little clearer.",
    "",
    "You can send it like:",
    "30 squares, 8/12 pitch, two story, one layer tear-off, architectural shingles",
    "",
    missingRequiredFields(job).length
      ? "Or ask 'what am I missing' and I'll list the next items I need."
      : "Or send 'estimate' and I'll price what we have."
  ]);
}

function buildTemplateReply(intent, job, conversation, updatedFields) {
  switch (intent) {
    case "reset_estimate":
      conversation.job = emptyRoofJob();
      conversation.lastEstimate = null;
      return "Got it. I cleared this roof and started fresh. Send the squares, pitch, stories, tear-off layers, and shingle choice when you're ready.";
    case "help":
      return helpReply();
    case "provide_measurement":
      return measurementReply(job, updatedFields || []);
    case "request_estimate":
      return estimateReply(job, conversation);
    case "explain_price":
      return explainPriceReply(job, conversation);
    case "lower_price":
      return lowerPriceReply();
    case "decking":
      return deckingReply(job, conversation);
    case "scope_detail":
      return scopeDetailReply(job);
    case "missing_info":
      return missingInfoReply(job);
    case "homeowner_response_help":
      return homeownerHelpReply(job, conversation);
    case "competitor_comparison":
      return competitorReply();
    case "field_checklist":
      return fieldChecklistReply();
    case "insurance_or_supplement":
      return insuranceReply();
    case "general_roofing_question":
      return generalRoofingReply(job);
    case "unclear":
    default:
      return unclearReply(job);
  }
}

// -----------------------------------------------------------------------------
// Telnyx outbound send
// -----------------------------------------------------------------------------

async function sendSms({ to, from, text }) {
  const apiKey = process.env.TELNYX_API_KEY;
  const telnyxFrom = from || process.env.TELNYX_PHONE_NUMBER || process.env.SMS_FROM_NUMBER;

  if (!apiKey || !telnyxFrom || !to) {
    console.log("[BidBuddy SMS] Outbound skipped. Missing TELNYX_API_KEY, from number, or recipient.");
    console.log("[BidBuddy SMS] Reply would have been:", text);
    return { skipped: true, reason: "missing_telnyx_config" };
  }

  const response = await fetch("https://api.telnyx.com/v2/messages", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({ from: telnyxFrom, to, text })
  });

  const responseBody = await response.text();
  if (!response.ok) {
    console.error("[BidBuddy SMS] Telnyx send failed", response.status, responseBody);
    return { ok: false, status: response.status, body: responseBody };
  }
  return { ok: true, status: response.status, body: responseBody };
}

// -----------------------------------------------------------------------------
// Public processing function
// -----------------------------------------------------------------------------

async function processIncomingSms({ from, to, text, companyId }) {
  const cleaned = cleanText(text);
  const phoneKey = getPhoneKey({ from, companyId });

  // *** DIAGNOSTIC LOGGING: log every inbound message, unconditionally,
  // right at the top, before any early-return path. This guarantees Render
  // logs show SOMETHING for every single text that reaches this function -
  // no more ambiguity about whether the webhook even got this far. ***
  console.log(`[BidBuddy SMS] Inbound message received.`, JSON.stringify({ from: normalizePhone(from), to, phoneKey, text: cleaned }));

  // -------------------- Compliance gate: deterministic, unchanged --------------------
  if (matchesKeyword(cleaned, OPT_OUT_KEYWORDS)) {
    const knownCompany = resolveEstimatorContext(from);
    recordOptOut(from, knownCompany ? knownCompany.companyId : null);
    return { reply: OPT_OUT_MESSAGE, intent: "opt_out", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: false, replySource: "compliance" };
  }
  if (matchesKeyword(cleaned, HELP_KEYWORDS)) {
    return { reply: HELP_MESSAGE, intent: "help_keyword", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: false, replySource: "compliance" };
  }
  if (matchesKeyword(cleaned, OPT_IN_KEYWORDS)) {
    const knownCompany = resolveEstimatorContext(from);
    recordOptIn(from, knownCompany ? knownCompany.companyId : null);
    return { reply: OPT_IN_MESSAGE, intent: "opt_in", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: false, replySource: "compliance" };
  }
  if (isOptedOut(from)) {
    return { reply: null, intent: "suppressed_opted_out", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: true, replySource: "compliance" };
  }

  // -------------------- Normal conversation flow --------------------
  const bucket = getOrCreatePhoneBucket(phoneKey);

  if (bucket.estimatorContext === null) {
    bucket.estimatorContext = resolveEstimatorContext(from) || false;
  }
  const estimatorContext = bucket.estimatorContext || null;

  // *** DIAGNOSTIC LOGGING: log the resolved (or unresolved) company for
  // this phone on every message, so you can see at a glance in Render logs
  // whether a given test number is actually mapped to the company you
  // expect it to be. ***
  console.log(
    `[BidBuddy SMS] Estimator context resolved.`,
    JSON.stringify({
      phoneKey,
      resolved: Boolean(estimatorContext),
      companyId: estimatorContext ? estimatorContext.companyId : null,
      companyName: estimatorContext ? estimatorContext.companyName : null
    })
  );

  const details = parseRoofDetails(cleaned);
  const intent = classifyIntent(cleaned, details);

  if (bucket.pendingAssignment) {
    const resolvedThread = resolvePendingAssignment(bucket, cleaned);
    if (resolvedThread) {
      const pending = bucket.pendingAssignment;
      if (pending.name) {
        resolvedThread.job.customerName = pending.name;
        resolvedThread.customerKey = normalizeCustomerKey(pending.name);
      }
      if (pending.address) {
        resolvedThread.job.customerAddress = pending.address;
      }
      resolvedThread.updatedAt = new Date().toISOString();
      bucket.activeThreadId = resolvedThread.id;
      bucket.pendingAssignment = null;

      if (resolvedThread.lastEstimate && estimatorContext) {
        persistToDatabase({ estimatorContext, job: resolvedThread.job, estimate: resolvedThread.lastEstimate, thread: resolvedThread, phoneKey });
      }

      const reply = `Got it - attached to the ${resolvedThread.job.squares ? resolvedThread.job.squares + " square " : ""}job. Send anything else on that one, or start the next job's details.`;
      resolvedThread.messages.push({
        at: new Date().toISOString(),
        from,
        to,
        inbound: cleaned,
        intent: "clarification_resolved",
        updatedFields: ["customerName", "customerAddress"],
        reply,
        replySource: "deterministic_clarification"
      });
      if (resolvedThread.messages.length > MAX_STORED_MESSAGES) {
        resolvedThread.messages = resolvedThread.messages.slice(-MAX_STORED_MESSAGES);
      }

      bucket.threads[resolvedThread.id] = resolvedThread;
      bucket.updatedAt = new Date().toISOString();
      conversationState[phoneKey] = bucket;
      saveState(conversationState);

      return {
        reply,
        intent: "clarification_resolved",
        job: resolvedThread.job,
        conversationKey: phoneKey,
        threadId: resolvedThread.id,
        estimatorContext: estimatorContext ? { companyId: estimatorContext.companyId, companyName: estimatorContext.companyName } : null,
        suppressed: false,
        replySource: "deterministic_clarification"
      };
    }
  }

  if (isBareCustomerInfoMessage(details)) {
    const alreadyMatchedByName = details.customerName ? findThreadByCustomerName(bucket, details.customerName) : null;
    const alreadyMatchedByAddress =
      !alreadyMatchedByName && details.customerAddress ? findThreadByCustomerAddress(bucket, details.customerAddress) : null;

    if (!alreadyMatchedByName && !alreadyMatchedByAddress) {
      const needingName = findThreadsNeedingCustomerName(bucket);
      if (needingName.length > 1) {
        bucket.pendingAssignment = {
          name: details.customerName || null,
          address: details.customerAddress || null,
          candidateThreadIds: needingName.map((t) => t.id),
          createdAt: new Date().toISOString()
        };
        const reply = buildClarificationReply(needingName);
        bucket.updatedAt = new Date().toISOString();
        conversationState[phoneKey] = bucket;
        saveState(conversationState);
        return {
          reply,
          intent: "clarify_customer_job",
          job: null,
          conversationKey: phoneKey,
          threadId: null,
          estimatorContext: estimatorContext ? { companyId: estimatorContext.companyId, companyName: estimatorContext.companyName } : null,
          suppressed: false,
          replySource: "deterministic_clarification"
        };
      }
    }
  }

  if (intent === "reset_estimate") {
    let thread = bucket.activeThreadId ? bucket.threads[bucket.activeThreadId] : null;
    if (!thread) {
      thread = emptyThread();
      bucket.threads[thread.id] = thread;
      bucket.activeThreadId = thread.id;
    }
    thread.job = emptyRoofJob();
    thread.lastEstimate = null;
    thread.dbEstimateId = null;
    thread.customerKey = null;
    thread.askedForCustomerInfo = false;
    const reply = "Got it. I cleared this roof and started fresh. Send the squares, pitch, stories, tear-off layers, and shingle choice when you're ready.";
    thread.updatedAt = new Date().toISOString();
    thread.messages.push({ at: new Date().toISOString(), from, to, inbound: cleaned, intent, updatedFields: [], reply });
    bucket.updatedAt = new Date().toISOString();
    conversationState[phoneKey] = bucket;
    saveState(conversationState);
    return { reply, intent, job: thread.job, conversationKey: phoneKey, threadId: thread.id, estimatorContext: null, suppressed: false, replySource: "deterministic_reset" };
  }

  const conversation = resolveActiveThread(bucket, cleaned, details);
  conversation.estimatorContext = estimatorContext;

  let updatedFields = [];
  updatedFields = mergeJobDetails(conversation.job, details);

  if (conversation.job.customerName) {
    conversation.customerKey = normalizeCustomerKey(conversation.job.customerName);
  }

  const previousEstimate = conversation.lastEstimate || null;
  const currentEstimate = tryCalculateEstimate(conversation.job, estimatorContext);

  let reply = null;
  let replySource = "template_fallback";

  if (aiReplyModule && typeof aiReplyModule.generateAiReply === "function") {
    const recentHistory = (conversation.messages || []).slice(-MAX_AI_HISTORY_TURNS);
    try {
      const aiText = await aiReplyModule.generateAiReply({
        companyName: estimatorContext ? estimatorContext.companyName : null,
        job: conversation.job,
        missingFields: missingRequiredFields(conversation.job),
        currentEstimate,
        previousEstimate,
        askedForCustomerInfo: conversation.askedForCustomerInfo,
        pricingProfile: estimatorContext ? estimatorContext.pricing : null,
        history: recentHistory,
        userText: cleaned
      });
      if (aiText) {
        reply = aiText;
        replySource = "ai";
        if (currentEstimate && !conversation.job.customerName && !conversation.askedForCustomerInfo) {
          conversation.askedForCustomerInfo = true;
        }
      }
    } catch (_) {
      // fall through to template fallback below
    }
  }

  if (!reply) {
    reply = buildTemplateReply(intent, conversation.job, conversation, updatedFields);
    replySource = "template_fallback";
  }

  if (currentEstimate) {
    conversation.lastEstimate = { ...currentEstimate, createdAt: new Date().toISOString() };
  }

  // *** THE FIX: write this thread's estimate (and customer name/address) to
  // the database every turn a full estimate exists. Now fully logged - see
  // persistToDatabase() above for exactly what gets printed on every path. ***
  if (currentEstimate && estimatorContext) {
    persistToDatabase({ estimatorContext, job: conversation.job, estimate: conversation.lastEstimate, thread: conversation, phoneKey });
  } else {
    // *** DIAGNOSTIC LOGGING: explicitly log WHY persistToDatabase was never
    // even called this turn, covering the two conditions the guard above
    // checks. This is the single most useful line for diagnosing "nothing
    // shows up on the dashboard" reports going forward. ***
    console.log(
      "[BidBuddy SMS] persistToDatabase NOT CALLED this turn.",
      JSON.stringify({
        phoneKey,
        hasCurrentEstimate: Boolean(currentEstimate),
        hasEstimatorContext: Boolean(estimatorContext),
        missingRequiredFields: missingRequiredFields(conversation.job)
      })
    );
  }

  conversation.updatedAt = new Date().toISOString();
  conversation.messages.push({ at: new Date().toISOString(), from, to, inbound: cleaned, intent, updatedFields, reply, replySource });
  if (conversation.messages.length > MAX_STORED_MESSAGES) {
    conversation.messages = conversation.messages.slice(-MAX_STORED_MESSAGES);
  }

  bucket.threads[conversation.id] = conversation;
  bucket.activeThreadId = conversation.id;
  bucket.updatedAt = new Date().toISOString();
  pruneOldThreads(bucket);

  conversationState[phoneKey] = bucket;
  saveState(conversationState);

  return {
    reply,
    intent,
    job: conversation.job,
    conversationKey: phoneKey,
    threadId: conversation.id,
    estimatorContext: estimatorContext ? { companyId: estimatorContext.companyId, companyName: estimatorContext.companyName } : null,
    suppressed: false,
    replySource
  };
}

// -----------------------------------------------------------------------------
// Express route handler
// -----------------------------------------------------------------------------

async function handleSms(req, res) {
  try {
    const body = req && req.body ? req.body : {};

    if (!isProcessableInboundEvent(body)) {
      if (res) return res.status(200).json({ ok: true, ignored: true });
      return { ok: true, ignored: true };
    }

    const payload = extractSmsPayload(req);
    const { from, to, text } = payload;

    if (!from || !text) {
      console.log("[BidBuddy SMS] handleSms: missing from or text, skipping.", JSON.stringify({ from, text }));
      if (res) return res.status(200).json({ ok: true, skipped: "missing_from_or_text" });
      return { ok: true, skipped: true };
    }

    const companyContext = resolveEstimatorContext(from);
    const companyId = companyContext ? companyContext.companyId : null;

    const result = await processIncomingSms({ from, to, text, companyId });

    if (result.reply) {
      await sendSms({ to: from, from: to, text: result.reply });
    }

    if (res) {
      return res.status(200).json({ ok: true, intent: result.intent, replySource: result.replySource, suppressed: result.suppressed });
    }
    return result;
  } catch (error) {
    console.error("[BidBuddy SMS] handler error", error);
    if (res) return res.status(200).json({ ok: false, error: "sms_handler_error" });
    return { ok: false, error };
  }
}

// -----------------------------------------------------------------------------
// Exports
// -----------------------------------------------------------------------------

module.exports = {
  handleSms,
  processIncomingSms,
  parseRoofDetails,
  classifyIntent,
  calculateEstimate,
  emptyRoofJob,
  missingRequiredFields,
  normalizePhone,
  isOptedOut,
  recordOptOut,
  recordOptIn
};
