"use strict";
/**
 * BidBuddy Roofing SMS Handler
 * Complete replacement file for lib/smsHandler.js
 *
 * ARCHITECTURE:
 * Compliance (STOP/HELP/START) and pricing math are 100% deterministic,
 * rule-based code. These are never generated by AI, for legal/accuracy
 * reasons - carrier keyword compliance and dollar figures must never
 * drift or be invented.
 *
 * The actual REPLY TEXT is generated conversationally by OpenAI
 * (lib/aiReply.js + lib/promptBuilder.js), grounded strictly in the
 * deterministic job state and computed estimate.
 *
 * If OPENAI_API_KEY is not set, or the OpenAI call fails/times out for
 * any reason, this file automatically falls back to the previous
 * template-based reply system (classifyIntent + buildReply) so SMS
 * never goes silent in production.
 *
 * *** FIX IN THIS REVISION (cross-job customer name/address mixing) ***
 * Root cause of the Bluff City bug: when an estimator sent job A's
 * measurements, THEN job B's measurements (which auto-starts a second
 * thread and makes it active), and only THEN sent job A's customer
 * name/address in its own follow-up message, the old resolveActiveThread()
 * logic only ever considered bucket.activeThreadId when deciding which
 * thread to attach an orphan name/address to. That meant job A's name
 * silently landed on job B's dashboard row instead of job A's - the exact
 * "wrong customer/address" symptom confirmed on Bluff City testing.
 *
 * This revision fixes it two ways:
 *   1. When a bare name/address message (no measurements) arrives and it
 *      does not match an existing customer by name or by address, EVERY
 *      thread on the phone that is still missing a name is now
 *      considered - not just the active one. If exactly one thread is
 *      missing a name, it is attached there correctly regardless of which
 *      thread is "active".
 *   2. If TWO OR MORE threads are missing a name at the same time (the
 *      genuinely ambiguous case that caused the bug), the system no
 *      longer guesses. It sends one short clarifying question ("job 1 or
 *      job 2?") and holds the name/address until the estimator answers,
 *      instead of silently mis-attaching it.
 *
 * This affects every tenant identically, since none of this logic is
 * keyed off a specific company.
 *
 * Expected usage from an Express route:
 *   const { handleSms } = require("./lib/smsHandler");
 *   app.post("/sms", handleSms);
 */

const fs = require("fs");
const path = require("path");

let aiReplyModule = null;
try {
  aiReplyModule = require("./aiReply");
} catch (_) {
  aiReplyModule = null;
}

// -----------------------------------------------------------------------------
// Optional pricing module loading (lib/roofingPricing.js — the real engine)
// -----------------------------------------------------------------------------

let pricingModule = null;
const pricingModuleCandidates = [
  "./roofingpricing",
  "./roofingPricing",
  "./pricing",
  "../lib/roofingpricing",
  "../lib/roofingPricing",
  "../lib/pricing"
];

for (const candidate of pricingModuleCandidates) {
  try {
    pricingModule = require(candidate);
    break;
  } catch (_) {
    // Keep trying. This file can still produce useful conversations without it.
  }
}

// -----------------------------------------------------------------------------
// Optional multi-tenant DB loading (companies, users, pricing_profiles, shingles,
// and estimates persistence)
// -----------------------------------------------------------------------------

let dbModule = null;
const dbModuleCandidates = ["./db", "../db", "./database", "../database"];
for (const candidate of dbModuleCandidates) {
  try {
    dbModule = require(candidate);
    break;
  } catch (_) {
    // Keep trying.
  }
}

function resolveEstimatorContext(fromPhone) {
  if (!dbModule || typeof dbModule.getUserByPhone !== "function") return null;
  try {
    const user = dbModule.getUserByPhone(fromPhone);
    if (!user) return null;
    const pricing = typeof dbModule.getPricing === "function" ? dbModule.getPricing(user.company_id) : null;
    if (!pricing) return null;
    return { user, companyId: user.company_id, companyName: user.company_name, pricing };
  } catch (_) {
    return null;
  }
}

function resolveShingle(estimatorContext, materialText) {
  if (!estimatorContext || !dbModule) return null;
  try {
    if (materialText && typeof dbModule.matchShingle === "function") {
      const matched = dbModule.matchShingle(estimatorContext.companyId, materialText);
      if (matched) return matched;
    }
    if (typeof dbModule.getDefaultShingle === "function") {
      return dbModule.getDefaultShingle(estimatorContext.companyId);
    }
  } catch (_) {
    // fall through
  }
  return null;
}

function mapJobForPricingEngine(job) {
  return {
    squares: job.squares,
    layers: job.tearOffLayers,
    pitch: parsePitchNumber(job.pitch),
    stories: job.stories,
    ridge_lf: job.ridgeLf,
    eave_lf: job.eaveRakeLf,
    valley_lf: job.valleyLf,
    penetrations: job.pipeBoots || job.penetrations,
    chimneys: job.chimneys,
    skylights: job.skylights,
    // Feeds roofingPricing.js's own dumpster inclusion logic directly, so
    // there is exactly ONE place (the real pricing engine) that decides
    // whether the dumpster fee is charged - never a second, separate adder
    // bolted on afterward, which previously double-billed it.
    //
    // NOTE the inversion: job.dumpsterRequested is null/true by default
    // (dumpster IS included unless explicitly declined), but
    // roofingPricing.js's calculateRoofEstimate() checks the opposite
    // polarity - dumpster_excluded - so it can default to false (included)
    // when nothing has been said at all. Only an explicit "customer's
    // supplying their own dumpster" (job.dumpsterRequested === false)
    // should exclude it.
    dumpster_excluded: job.dumpsterRequested === false
  };
}

// -----------------------------------------------------------------------------
// Compliance: STOP / HELP / START keyword handling — deterministic, unchanged
// -----------------------------------------------------------------------------
// These keyword lists and confirmation messages are kept in exact sync with
// what is registered on the BidBuddy USA LLC 10DLC campaign in the Telnyx
// Mission Control Portal (Messaging > 10DLC > Campaigns).

const OPT_OUT_KEYWORDS = ["STOP", "UNSUBSCRIBE", "CANCEL"];
const OPT_IN_KEYWORDS = ["START", "YES"];
const HELP_KEYWORDS = ["HELP"];

const OPT_IN_MESSAGE =
  "You have agreed to receive SMS updates from BidBuddy USA LLC. Msg freq may vary. Std msg & data rates apply. Reply STOP to opt out, HELP for help.";
const OPT_OUT_MESSAGE =
  "BidBuddy USA LLC: You have been unsubscribed and will no longer receive messages from us. Reply HELP for assistance.";
const HELP_MESSAGE =
  "BidBuddy USA LLC: For help, reply HELP or contact us at +19012889044. Msg frequency varies. Msg&data rates may apply. Reply STOP to opt out.";

function matchesKeyword(cleanedText, keywordList) {
  const normalized = String(cleanedText || "")
    .trim()
    .replace(/[.!?,;:]+$/g, "")
    .toUpperCase();
  return keywordList.includes(normalized);
}

// -----------------------------------------------------------------------------
// Opt-out persistence: database-backed (survives redeploys/restarts), with a
// local JSON file used ONLY as an automatic fallback if the database call
// throws.
// -----------------------------------------------------------------------------

const OPT_OUT_STATE_FILE =
  process.env.BIDBUDDY_OPTOUT_STATE_FILE ||
  path.join(process.env.BIDBUDDY_DATA_DIR || path.join(process.cwd(), "data"), "sms-optouts.json");

function ensureDataDirFor(filePath) {
  const dir = path.dirname(filePath);
  try {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  } catch (_) {
    // Read-only filesystem fallback: in-memory only for this process lifetime.
  }
}

function loadOptOutState() {
  try {
    ensureDataDirFor(OPT_OUT_STATE_FILE);
    if (!fs.existsSync(OPT_OUT_STATE_FILE)) return {};
    const raw = fs.readFileSync(OPT_OUT_STATE_FILE, "utf8");
    return JSON.parse(raw || "{}");
  } catch (_) {
    return {};
  }
}

function saveOptOutState(state) {
  try {
    ensureDataDirFor(OPT_OUT_STATE_FILE);
    fs.writeFileSync(OPT_OUT_STATE_FILE, JSON.stringify(state, null, 2));
  } catch (_) {
    // Do not fail SMS response if state save fails.
  }
}

let optOutState = loadOptOutState();

function hasDbOptOutSupport() {
  return Boolean(
    dbModule &&
      typeof dbModule.isPhoneOptedOut === "function" &&
      typeof dbModule.recordOptOut === "function" &&
      typeof dbModule.recordOptIn === "function"
  );
}

function isOptedOut(phone) {
  if (hasDbOptOutSupport()) {
    try {
      return dbModule.isPhoneOptedOut(phone);
    } catch (_) {
      // fall through to JSON fallback below
    }
  }
  const key = normalizePhone(phone);
  return Boolean(optOutState[key] && optOutState[key].optedOut);
}

function recordOptOut(phone, companyId) {
  if (hasDbOptOutSupport()) {
    try {
      dbModule.recordOptOut(phone, companyId || null);
      return;
    } catch (_) {
      // fall through
    }
  }
  const key = normalizePhone(phone);
  optOutState[key] = optOutState[key] || {};
  optOutState[key].optedOut = true;
  optOutState[key].optedOutAt = new Date().toISOString();
  saveOptOutState(optOutState);
}

function recordOptIn(phone, companyId) {
  if (hasDbOptOutSupport()) {
    try {
      dbModule.recordOptIn(phone, companyId || null);
      return;
    } catch (_) {
      // fall through
    }
  }
  const key = normalizePhone(phone);
  optOutState[key] = optOutState[key] || {};
  optOutState[key].optedOut = false;
  optOutState[key].optedInAt = new Date().toISOString();
  saveOptOutState(optOutState);
}

// -----------------------------------------------------------------------------
// Lightweight context store
// -----------------------------------------------------------------------------
//
// MULTI-JOB-PER-PHONE ARCHITECTURE:
// One estimator phone number can legitimately be mid-conversation about
// MULTIPLE different customers' roofs at once (e.g. bidding job A in the
// morning, job B in the afternoon, then a homeowner from job A texts back
// a follow-up question days later). This file keeps a per-phone BUCKET
// containing one or more THREADS. Each thread is one customer's job (job,
// messages, lastEstimate, dbEstimateId, etc) - so it still maps 1:1 to a
// single dashboard/estimates row. The bucket tracks which thread is
// currently "active" and routes each inbound message to the correct thread
// using resolveActiveThread() below.

const DATA_DIR = process.env.BIDBUDDY_DATA_DIR || path.join(process.cwd(), "data");
const STATE_FILE = process.env.BIDBUDDY_SMS_STATE_FILE || path.join(DATA_DIR, "sms-conversations.json");
const MAX_STORED_MESSAGES = 20;
const MAX_AI_HISTORY_TURNS = 8;
// Ceiling on how many customer threads a single phone number can accumulate
// before old, ALREADY-COMPLETED threads start getting pruned (never prunes
// the active thread or a job still being built) - keeps a long-lived demo
// or production number's state file from growing without bound.
const MAX_THREADS_PER_PHONE = Number(process.env.BIDBUDDY_MAX_THREADS_PER_PHONE || 25);

function ensureDataDir() {
  try {
    if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  } catch (_) {
    // read-only fallback: in-memory only
  }
}

function loadState() {
  try {
    ensureDataDir();
    if (!fs.existsSync(STATE_FILE)) return {};
    const raw = fs.readFileSync(STATE_FILE, "utf8");
    return JSON.parse(raw || "{}");
  } catch (_) {
    return {};
  }
}

function saveState(state) {
  try {
    ensureDataDir();
    fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
  } catch (_) {
    // Do not fail SMS response if state save fails.
  }
}

let conversationState = loadState();

function normalizePhone(phone) {
  return String(phone || "unknown")
    .trim()
    .replace(/[^+0-9]/g, "");
}

// Phone-level key. NOTE: this identifies the PHYSICAL PHONE/estimator, not
// an individual job - a single phone's bucket can hold many customer
// threads at once. Kept the same name/shape as before
// (${companyId}:${normalizedPhone}) so existing dashboard/portal code
// that already keys off this string keeps working unchanged.
function getPhoneKey({ from, companyId }) {
  const normalized = normalizePhone(from);
  return `${companyId || "default"}:${normalized}`;
}

function makeThreadId() {
  return `t_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

// One THREAD = one customer's job = one dashboard/estimates row.
function emptyThread() {
  return {
    id: makeThreadId(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    job: emptyRoofJob(),
    messages: [],
    lastEstimate: null,
    // Tracks whether we've already nudged for the customer's name/address
    // once a full estimate is ready, so the ask happens ONE time per job
    // rather than repeating on every follow-up question.
    askedForCustomerInfo: false,
    // Tracks the database row id (if any) that THIS THREAD's estimate was
    // saved under, so later updates (e.g. customer name/address arriving
    // in a LATER message than the measurements) update that SAME row
    // instead of being silently skipped or creating a duplicate row.
    dbEstimateId: null,
    // Normalized (lowercase, trimmed) customer name used to re-identify
    // this exact thread later if the estimator mentions this customer's
    // name again after switching to (or starting) a different customer.
    customerKey: null
  };
}

// A BUCKET is everything known about one physical phone number: the
// resolved estimator/company context (same for every job that phone ever
// texts about) plus a map of all customer threads that phone has open.
function getOrCreatePhoneBucket(key) {
  if (!conversationState[key]) {
    conversationState[key] = {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      estimatorContext: null,
      activeThreadId: null,
      threads: {},
      // Holds an in-flight "which job is this for?" clarification, if one
      // has been asked and not yet answered. See isBareCustomerInfoMessage
      // / resolvePendingAssignment below.
      pendingAssignment: null
    };
  }
  // Backward-compat: if this phone's saved state predates the multi-thread
  // rebuild (it still has the OLD single-job shape - a top-level job
  // field instead of threads), migrate its one existing job into a
  // single thread automatically instead of discarding in-flight work.
  const bucket = conversationState[key];
  if (!bucket.threads) {
    const migrated = emptyThread();
    migrated.job = bucket.job || emptyRoofJob();
    migrated.messages = bucket.messages || [];
    migrated.lastEstimate = bucket.lastEstimate || null;
    migrated.askedForCustomerInfo = Boolean(bucket.askedForCustomerInfo);
    migrated.dbEstimateId = bucket.dbEstimateId || null;
    migrated.customerKey = migrated.job.customerName ? normalizeCustomerKey(migrated.job.customerName) : null;
    conversationState[key] = {
      createdAt: bucket.createdAt || new Date().toISOString(),
      updatedAt: bucket.updatedAt || new Date().toISOString(),
      estimatorContext: bucket.estimatorContext || null,
      activeThreadId: migrated.id,
      threads: { [migrated.id]: migrated },
      pendingAssignment: null
    };
  }
  if (conversationState[key].pendingAssignment === undefined) {
    conversationState[key].pendingAssignment = null;
  }
  return conversationState[key];
}

function normalizeCustomerKey(name) {
  return String(name || "").trim().toLowerCase();
}

function normalizeAddressKey(address) {
  return String(address || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

function findThreadByCustomerName(bucket, name) {
  const key = normalizeCustomerKey(name);
  if (!key) return null;
  for (const threadId of Object.keys(bucket.threads)) {
    const t = bucket.threads[threadId];
    if (t.customerKey && t.customerKey === key) return t;
  }
  return null;
}

// Lets a known street address re-identify the correct thread even when the
// name wasn't repeated - e.g. the estimator sends "313 Johnsborough Dr,
// what's the range again" days later with no name attached.
function findThreadByCustomerAddress(bucket, address) {
  const key = normalizeAddressKey(address);
  if (!key) return null;
  for (const threadId of Object.keys(bucket.threads)) {
    const t = bucket.threads[threadId];
    const tKey = normalizeAddressKey(t.job && t.job.customerAddress);
    if (tKey && tKey === key) return t;
  }
  return null;
}

// *** PART OF THE FIX ***
// Returns every thread on this phone that does NOT yet have a customer
// name attached, sorted most-recently-updated first. Used both to decide
// whether an orphan name/address is unambiguous (exactly one candidate)
// and to build the clarifying question when it is not.
function findThreadsNeedingCustomerName(bucket) {
  return Object.keys(bucket.threads)
    .map((id) => bucket.threads[id])
    .filter((t) => !t.customerKey && !(t.job && t.job.customerName))
    .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
}

// A thread counts as "complete" once it has every required measurement AND
// has actually been priced at least once - this is the signal used below
// to decide whether the NEXT message on this phone should keep building
// the same job, or should be treated as the start of a different one.
function isThreadComplete(thread) {
  return Boolean(thread && thread.job && missingRequiredFields(thread.job).length === 0 && thread.lastEstimate);
}

// Heuristic: does this inbound message look like the start of a brand-new
// job description? "squares" is used as the anchor signal because almost
// every real-world job description opens with a squares figure.
function looksLikeNewJobStart(details) {
  return Boolean(details && details.squares !== undefined && details.squares !== null);
}

// Fields that, if present, mean this message is describing actual roof
// measurements/scope - as opposed to being a "bare" customer name/address
// message with nothing else in it.
const CORE_MEASUREMENT_KEYS_FOR_BARE_CHECK = [
  "squares",
  "roofAreaSqFt",
  "pitch",
  "stories",
  "tearOffLayers",
  "material",
  "ridgeLf",
  "eaveRakeLf",
  "valleyLf",
  "chimneys",
  "skylights",
  "pipeBoots",
  "deckingSheets",
  "deckingSqFt"
];

// *** PART OF THE FIX ***
// True when an inbound message contains a customer name and/or address but
// NO job measurements at all - e.g. "this is for customer James Ellis, 123
// Oak St". These are the risky messages: with no measurements of their own
// to anchor them to a specific roof, the only signal for which job they
// belong to is which thread(s) on this phone are currently missing a name.
function isBareCustomerInfoMessage(details) {
  if (!details) return false;
  if (!details.customerName && !details.customerAddress) return false;
  return !CORE_MEASUREMENT_KEYS_FOR_BARE_CHECK.some(
    (k) => details[k] !== undefined && details[k] !== null && details[k] !== ""
  );
}

// Decides which THREAD (customer job) this inbound message belongs to.
// Rules, in order:
//   1. Message names a customer (or address) that already matches an
//      existing thread -> switch back to that thread.
//   2. Message names a customer with no existing match, and exactly ONE
//      thread on this phone is missing a customer name -> attach it there,
//      regardless of whether that thread is currently "active". (This is
//      the core fix: previously step 2 only ever checked the active
//      thread, which mis-attached names when the estimator had already
//      moved on to a different job.)
//   3. Message names a customer with no existing match, and there is NOT
//      exactly one candidate (zero, because everyone already has a name;
//      or the message ALSO contains its own measurements, so it is
//      unambiguously describing a brand-new job) -> start a fresh thread.
//   4. No customer name in this message, and the active thread is still
//      being built -> keep accumulating on it.
//   5. No customer name in this message, active thread already fully
//      priced, and this message looks like a new job start -> auto-start
//      a fresh thread with no reset keyword required.
//   6. Otherwise -> treat as a follow-up question/adjustment on the job
//      that was just completed.
//
// NOTE: genuinely ambiguous bare name/address messages (2+ threads missing
// a name, with NO measurements of their own) are intercepted earlier, in
// processIncomingSms, by the clarifying-question guardrail, before this
// function is ever called for that message.
function resolveActiveThread(bucket, cleaned, details) {
  const candidateName = (details && details.customerName) || extractCustomerName(cleaned);
  const candidateAddress = (details && details.customerAddress) || extractCustomerAddress(cleaned);

  if (candidateName) {
    const matchedByName = findThreadByCustomerName(bucket, candidateName);
    if (matchedByName) {
      bucket.activeThreadId = matchedByName.id;
      return matchedByName;
    }
  }

  if (candidateAddress) {
    const matchedByAddress = findThreadByCustomerAddress(bucket, candidateAddress);
    if (matchedByAddress) {
      bucket.activeThreadId = matchedByAddress.id;
      return matchedByAddress;
    }
  }

  if (candidateName) {
    const needingName = findThreadsNeedingCustomerName(bucket);
    if (needingName.length === 1) {
      const only = needingName[0];
      only.customerKey = normalizeCustomerKey(candidateName);
      bucket.activeThreadId = only.id;
      return only;
    }
    // Either zero candidates (everyone already has a name) or this
    // message carries its own measurements alongside the name (so it is
    // unambiguously a brand-new job) - either way, start fresh.
    const fresh = emptyThread();
    fresh.customerKey = normalizeCustomerKey(candidateName);
    bucket.threads[fresh.id] = fresh;
    bucket.activeThreadId = fresh.id;
    return fresh;
  }

  const active = bucket.activeThreadId ? bucket.threads[bucket.activeThreadId] : null;
  if (!active) {
    const fresh = emptyThread();
    bucket.threads[fresh.id] = fresh;
    bucket.activeThreadId = fresh.id;
    return fresh;
  }

  if (!isThreadComplete(active)) {
    return active;
  }

  if (looksLikeNewJobStart(details)) {
    const fresh = emptyThread();
    bucket.threads[fresh.id] = fresh;
    bucket.activeThreadId = fresh.id;
    return fresh;
  }

  return active;
}

// Prevents a long-lived phone number's state file from growing forever.
// Only ever removes threads that are (a) not the currently active one and
// (b) already fully priced - an in-progress job is never pruned.
function pruneOldThreads(bucket) {
  const ids = Object.keys(bucket.threads);
  if (ids.length <= MAX_THREADS_PER_PHONE) return;
  const removable = ids
    .filter((id) => id !== bucket.activeThreadId && isThreadComplete(bucket.threads[id]))
    .sort((a, b) => new Date(bucket.threads[a].updatedAt).getTime() - new Date(bucket.threads[b].updatedAt).getTime());
  let overflow = ids.length - MAX_THREADS_PER_PHONE;
  for (const id of removable) {
    if (overflow <= 0) break;
    delete bucket.threads[id];
    overflow--;
  }
}

function emptyRoofJob() {
  return {
    trade: "roofing",
    customerName: null,
    customerAddress: null,
    squares: null,
    roofAreaSqFt: null,
    pitch: null,
    stories: null,
    access: null,
    tearOffLayers: null,
    material: null,
    complexity: null,
    ridgeLf: null,
    eaveRakeLf: null,
    valleyLf: null,
    chimneys: null,
    skylights: null,
    pipeBoots: null,
    penetrations: null,
    deckingSheets: null,
    deckingSqFt: null,
    deckingCondition: null,
    dumpAccess: null,
    // Dumpster/disposal is INCLUDED BY DEFAULT on every job (tear-off nearly
    // always needs disposal) - this only needs to be set to false when the
    // estimator explicitly says the customer is supplying their own
    // dumpster or no disposal fee applies. null/undefined = default-included.
    dumpsterRequested: null,
    permitRequired: null,
    ventilation: null,
    flashingScope: null,
    notes: []
  };
}

// -----------------------------------------------------------------------------
// Incoming SMS parsing helpers
// -----------------------------------------------------------------------------

// Telnyx sends webhooks for THREE distinct event types to the same
// configured webhook URL: message.received (real inbound SMS), message.sent
// (confirmation of OUR OWN outbound reply), and message.finalized (our own
// outbound reply's delivery status). Only message.received should ever be
// processed - otherwise the app treats its own replies as new inbound
// messages, causing a self-loop and "Invalid source number" send failures.
function getTelnyxEventType(body) {
  return body && body.data && body.data.event_type ? body.data.event_type : null;
}

function isProcessableInboundEvent(body) {
  const eventType = getTelnyxEventType(body);
  if (eventType === null) return true; // non-Telnyx / test payload, allow through
  return eventType === "message.received";
}

function extractSmsPayload(req) {
  const body = req && req.body ? req.body : {};

  const telnyxPayload = body.data && body.data.payload ? body.data.payload : null;
  if (telnyxPayload) {
    return {
      from: telnyxPayload.from && telnyxPayload.from.phone_number,
      to: telnyxPayload.to && telnyxPayload.to.length ? telnyxPayload.to[0].phone_number : undefined,
      text: telnyxPayload.text || telnyxPayload.body || "",
      provider: "telnyx",
      eventType: getTelnyxEventType(body),
      raw: body
    };
  }

  return {
    from: body.From || body.from || body.sender || body.phone || body.msisdn,
    to: body.To || body.to || body.recipient,
    text: body.Body || body.body || body.text || body.message || "",
    provider: body.provider || "unknown",
    eventType: null,
    raw: body
  };
}

function cleanText(text) {
  return String(text || "")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function lower(text) {
  return cleanText(text).toLowerCase();
}

function numberFromMatch(match) {
  if (!match || !match[1]) return null;
  const n = Number(String(match[1]).replace(/,/g, ""));
  return Number.isFinite(n) ? n : null;
}

function titleCase(str) {
  return String(str || "")
    .toLowerCase()
    .replace(/\b([a-z])/g, (c) => c.toUpperCase());
}

// Matches phrasing like "this is for customer James Ellis", "for customer
// James Ellis", "customer name is James Ellis", "customer: James Ellis".
// Runs against the ORIGINAL (non-lowercased) text so the captured name
// keeps its natural casing before being title-cased for storage/display.
const CUSTOMER_NAME_RE =
  /\b(?:this is for customer|for customer|customer(?:'s)? name is|customer name|customer is|customer:)\s+([A-Za-z][A-Za-z'.-]*(?:\s+[A-Za-z][A-Za-z'.-]*){0,3})/i;

// Words that can get accidentally swept into the name capture group when a
// customer/address message runs together, e.g. "customer is Kristy Smith
// and address 313 Johnsborough drive..." would otherwise capture "Kristy
// Smith and address" as the name. We strip ALL trailing filler words (not
// just one) so multi-word run-ons like "... and address" get fully removed.
const NAME_TRAILING_STOPWORDS = new Set(["at", "on", "near", "address", "is", "for", "and", "located"]);

// Guards against false positives where "customer is ..." is describing
// something OTHER than the customer's name - e.g. "customer is supplying
// their own dumpster" would otherwise be captured as customerName =
// "Supplying Their Own Dumpster". If the capture's first word is one of
// these non-name descriptor/verb words, reject the match entirely rather
// than storing garbage into the customer record.
const NAME_LEADING_REJECT_WORDS = new Set([
  "supplying", "providing", "bringing", "using", "getting", "renting",
  "paying", "handling", "taking", "doing", "going", "not", "already",
  "still", "unknown", "unsure", "waiting", "responsible",
  "aware", "ok", "okay", "fine", "good", "happy", "unhappy"
]);

function extractCustomerName(text) {
  const m = String(text || "").match(CUSTOMER_NAME_RE);
  if (!m) return null;
  let words = m[1]
    .trim()
    .replace(/[,.]+$/, "")
    .split(/\s+/);
  while (words.length && NAME_TRAILING_STOPWORDS.has(words[words.length - 1].toLowerCase())) {
    words.pop();
  }
  if (!words.length) return null;
  if (NAME_LEADING_REJECT_WORDS.has(words[0].toLowerCase())) return null;
  const name = words.join(" ").trim();
  return name ? titleCase(name) : null;
}

// Matches a US-style street address: house number + street name + a
// recognized street-type suffix, optionally followed by city/state/zip.
const STREET_SUFFIX =
  "(?:street|st|avenue|ave|road|rd|drive|dr|lane|ln|court|ct|boulevard|blvd|way|place|pl|circle|cir|trail|trl|parkway|pkwy|highway|hwy)";
const ADDRESS_RE = new RegExp(
  "\\b(\\d{1,6}\\s+[A-Za-z0-9][A-Za-z0-9.'-]*(?:\\s+[A-Za-z0-9][A-Za-z0-9.'-]*){0,4}\\s+" +
    STREET_SUFFIX +
    "\\.?" +
    "(?:\\s*,?\\s*[A-Za-z][A-Za-z\\s]{1,24})?(?:\\s*,?\\s*[A-Za-z]{2})?(?:\\s*\\d{5}(?:-\\d{4})?)?)",
  "i"
);

function extractCustomerAddress(text) {
  const m = String(text || "").match(ADDRESS_RE);
  if (!m) return null;
  return m[1].trim().replace(/\s+/g, " ");
}

function parseRoofDetails(text) {
  const msg = lower(text);
  const details = {};
  const notes = [];

  let m = msg.match(/(?:^|\b)(\d+(?:\.\d+)?)\s*(?:squares|square|sqrs|sqs|sq)\b/);
  if (m) details.squares = numberFromMatch(m);

  m = msg.match(/(?:^|\b)(\d{3,6}(?:\.\d+)?)\s*(?:sf|sqft|sq ft|square feet)\b/);
  if (m) {
    details.roofAreaSqFt = numberFromMatch(m);
    if (!details.squares) details.squares = Math.round((details.roofAreaSqFt / 100) * 10) / 10;
  }

  m = msg.match(/\b(\d{1,2})\s*\/\s*12\b/);
  if (m) details.pitch = `${m[1]}/12`;
  if (!details.pitch) {
    m = msg.match(/\b(\d{1,2})\s*(?:pitch|slope)\b/);
    if (m) details.pitch = `${m[1]}/12`;
  }

  if (/\b(one|1)[ -]?(story|storey)\b/.test(msg) || /\bsingle story\b/.test(msg)) details.stories = 1;
  if (/\b(two|2)[ -]?(story|storey)\b/.test(msg)) details.stories = 2;
  if (/\b(three|3)[ -]?(story|storey)\b/.test(msg)) details.stories = 3;

  if (/\bsteep\b/.test(msg)) details.access = "steep";
  if (/\bwalkable\b/.test(msg)) details.access = "walkable";
  if (/\bhard access|tight access|bad access|limited access\b/.test(msg)) details.access = "limited";

  m = msg.match(/\b(\d+)\s*(?:layer|layers)\b/);
  if (m && /tear ?off|remove|existing|old roof|shingle/.test(msg)) details.tearOffLayers = numberFromMatch(m);
  if (/\bone layer\b/.test(msg) && /tear ?off|remove|existing|old roof|shingle/.test(msg)) details.tearOffLayers = 1;
  if (/\btwo layers\b/.test(msg) && /tear ?off|remove|existing|old roof|shingle/.test(msg)) details.tearOffLayers = 2;
  if (/\bno tear ?off|overlay|layover|recover\b/.test(msg)) details.tearOffLayers = 0;

  if (/\barchitectural|dimensional|30 year|laminate\b/.test(msg)) details.material = "architectural shingles";
  if (/\b3 tab|three tab|3-tab\b/.test(msg)) details.material = "3-tab shingles";
  if (/\bdesigner|premium|presidential|grand manor|carriage\b/.test(msg)) details.material = "designer shingles";
  if (/\bmetal|standing seam|r panel|corrugated\b/.test(msg)) details.material = "metal roofing";
  if (/\btile roof|clay tile|concrete tile\b/.test(msg)) details.material = "tile roofing";
  if (/\bslate\b/.test(msg)) details.material = "slate roofing";

  if (/\bsimple gable|straight gable|easy gable\b/.test(msg)) details.complexity = "simple";
  if (/\bhip roof\b/.test(msg)) details.complexity = "moderate";
  if (/\bcut up|cut-up|complex|lots of valleys|many valleys|dormers\b/.test(msg)) details.complexity = "complex";

  m = msg.match(/\b(\d+(?:\.\d+)?)\s*(?:lf|linear feet|feet|ft)\s*(?:of\s*)?(?:ridge|ridge cap)\b/);
  if (m) details.ridgeLf = numberFromMatch(m);
  m = msg.match(/\b(\d+(?:\.\d+)?)\s*(?:lf|linear feet|feet|ft)\s*(?:of\s*)?(?:eave|eaves|rake|rakes|eave rake|eave\/rake)\b/);
  if (m) details.eaveRakeLf = numberFromMatch(m);
  m = msg.match(/\b(\d+(?:\.\d+)?)\s*(?:lf|linear feet|feet|ft)\s*(?:of\s*)?(?:valley|valleys)\b/);
  if (m) details.valleyLf = numberFromMatch(m);

  m = msg.match(/\b(\d+)\s*(?:chimney|chimneys)\b/);
  if (m) details.chimneys = numberFromMatch(m);
  m = msg.match(/\b(\d+)\s*(?:skylight|skylights)\b/);
  if (m) details.skylights = numberFromMatch(m);
  m = msg.match(/\b(\d+)\s*(?:pipe boot|pipe boots|boots|pipes|penetrations|vents)\b/);
  if (m) details.pipeBoots = numberFromMatch(m);

  m = msg.match(/\b(\d+)\s*(?:sheet|sheets)\b/);
  if (m && /deck|decking|plywood|osb|sheathing/.test(msg)) details.deckingSheets = numberFromMatch(m);
  m = msg.match(/\b(\d{2,5})\s*(?:sf|sqft|sq ft|square feet)\s*(?:decking|deck|sheathing)\b/);
  if (m) details.deckingSqFt = numberFromMatch(m);
  if (/\bbad decking|soft decking|rotten decking|decking is bad|bad deck|soft spots|delaminated\b/.test(msg)) {
    details.deckingCondition = "suspect or damaged";
  }

  if (/\bdumpster|dump access|driveway access|haul off|disposal\b/.test(msg)) notes.push(text);

  // Dumpster/disposal PRICING flag. Dumpster is INCLUDED BY DEFAULT on every
  // job, so the only meaningful signal to detect here is an EXPLICIT
  // exclusion - "customer is supplying their own dumpster", "no dumpster
  // needed", etc.
  const DUMPSTER_NEGATION_RE =
    /\b(?:no|not|don't|won't|without|skip)\b[^.]{0,20}\bdumpster\b|\bcustomer\s+(?:has|is\s+supplying|providing|bringing)\s+(?:a\s+|the\s+|their\s+own\s+)?dumpster\b|\balready\s+has\s+a\s+dumpster\b/;
  if (DUMPSTER_NEGATION_RE.test(msg)) details.dumpsterRequested = false;

  if (/\bpermit|permits\b/.test(msg)) details.permitRequired = !/no permit|not required/.test(msg);
  if (/\bridge vent|box vents|ventilation|intake|exhaust\b/.test(msg)) details.ventilation = text;
  if (/\bflashing|step flashing|counter flashing|apron flashing|wall flashing\b/.test(msg)) details.flashingScope = text;

  const customerName = extractCustomerName(text);
  if (customerName) details.customerName = customerName;
  const customerAddress = extractCustomerAddress(text);
  if (customerAddress) details.customerAddress = customerAddress;

  if (notes.length) details.notes = notes;
  return details;
}

function mergeJobDetails(job, details) {
  const updatedFields = [];
  for (const [key, value] of Object.entries(details || {})) {
    if (value === null || value === undefined || value === "") continue;
    if (key === "notes") {
      job.notes = Array.isArray(job.notes) ? job.notes : [];
      for (const note of value) job.notes.push(note);
      updatedFields.push("notes");
      continue;
    }
    job[key] = value;
    updatedFields.push(key);
  }
  return updatedFields;
}

// -----------------------------------------------------------------------------
// Intent classification — retained ONLY as the fallback path's routing logic
// and for lightweight logging/analytics. It no longer determines the primary
// reply when AI generation is available and succeeds.
// -----------------------------------------------------------------------------

const CORE_MEASUREMENT_FIELDS = ["squares", "pitch", "stories", "tearOffLayers", "material"];

function hasCoreMeasurementUpdate(details) {
  if (!details) return false;
  return CORE_MEASUREMENT_FIELDS.some(
    (field) => details[field] !== undefined && details[field] !== null && details[field] !== ""
  );
}

const EXPLAIN_TRIGGER_RE =
  /\b(why|expensive|so high|too high|too much|high|cost driver|breakdown|explain|difference|delta|changed|change|went up|went down|different)\b/;

function classifyIntent(text, details) {
  const msg = lower(text);

  if (/\b(reset|start over|new roof|new estimate|clear this)\b/.test(msg)) return "reset_estimate";
  if (/\b(help|what can you do)\b/.test(msg)) return "help";
  if (/\b(homeowner|customer|explain to|tell them|say to them)\b/.test(msg)) return "homeowner_response_help";
  if (EXPLAIN_TRIGGER_RE.test(msg)) return "explain_price";
  if (/\b(quote|estimate|price|range|rough number|how much|total|cost)\b/.test(msg)) return "request_estimate";
  if (/\b(cheaper|lower|save money|value engineer|reduce)\b/.test(msg)) return "lower_price";
  if (/\b(competitor|another roofer|other bid|cheaper bid|match)\b/.test(msg)) return "competitor_comparison";
  if (/\b(missing|need from me|what else|what do you need)\b/.test(msg)) return "missing_info";
  if (/\b(check before i leave|field checklist|look for|inspect|before leaving|driveway)\b/.test(msg)) return "field_checklist";
  if (/\b(insurance|supplement|claim|adjuster|storm|hail|wind)\b/.test(msg)) return "insurance_or_supplement";
  if (hasCoreMeasurementUpdate(details)) return "provide_measurement";
  if (/\b(decking|deck|sheathing|plywood|osb|sheets)\b/.test(msg)) return "decking";
  if (/\b(chimney|flashing|skylight|pipe boot|penetration|valley|ventilation|ridge vent)\b/.test(msg)) return "scope_detail";
  if (details && Object.keys(details).length > 0) return "provide_measurement";
  if (msg.length < 8) return "unclear";

  return "general_roofing_question";
}

// -----------------------------------------------------------------------------
// Roofing estimate logic — deterministic, unchanged. This is the ONLY source
// of dollar figures anywhere in the app, whether the AI or the template
// fallback is generating the reply text around those numbers.
// -----------------------------------------------------------------------------

const REQUIRED_FIELDS = ["squares", "pitch", "stories", "tearOffLayers", "material"];

function missingRequiredFields(job) {
  return REQUIRED_FIELDS.filter((field) => job[field] === null || job[field] === undefined || job[field] === "");
}

function formatFieldName(field) {
  const names = {
    squares: "squares",
    pitch: "pitch",
    stories: "one-story or two-story access",
    tearOffLayers: "tear-off layer count",
    material: "shingle or material choice"
  };
  return names[field] || field;
}

function knownJobBullets(job) {
  const bullets = [];
  if (job.squares) bullets.push(`${job.squares} squares`);
  if (job.pitch) bullets.push(`${job.pitch} pitch`);
  if (job.stories) bullets.push(`${job.stories}-story access`);
  if (job.tearOffLayers !== null && job.tearOffLayers !== undefined) {
    bullets.push(`${job.tearOffLayers} tear-off layer${job.tearOffLayers === 1 ? "" : "s"}`);
  }
  if (job.material) bullets.push(job.material);
  if (job.complexity) bullets.push(`${job.complexity} roof complexity`);
  if (job.chimneys !== null && job.chimneys !== undefined) bullets.push(`${job.chimneys} chimney${job.chimneys === 1 ? "" : "s"}`);
  if (job.skylights !== null && job.skylights !== undefined) bullets.push(`${job.skylights} skylight${job.skylights === 1 ? "" : "s"}`);
  if (job.pipeBoots !== null && job.pipeBoots !== undefined) {
    bullets.push(`${job.pipeBoots} pipe boot/penetration${job.pipeBoots === 1 ? "" : "s"}`);
  }
  if (job.deckingSheets) bullets.push(`${job.deckingSheets} decking sheet${job.deckingSheets === 1 ? "" : "s"} as an adder`);
  if (job.deckingCondition) bullets.push(`decking condition: ${job.deckingCondition}`);
  if (job.dumpsterRequested === false) bullets.push("no dumpster needed - customer/estimator supplying their own (disposal fee removed)");
  return bullets;
}

function parsePitchNumber(pitch) {
  const m = String(pitch || "").match(/(\d{1,2})/);
  return m ? Number(m[1]) : null;
}

function calculateDeckingAdder(job) {
  const deckSheetAdder = Number(process.env.ROOFING_DECK_SHEET_ADDER || 95);
  let deckingLow = 0;
  let deckingHigh = 0;
  if (job.deckingSheets) {
    deckingLow = Number(job.deckingSheets) * deckSheetAdder;
    deckingHigh = Number(job.deckingSheets) * Math.round(deckSheetAdder * 1.25);
  }
  return { deckingLow, deckingHigh };
}

// Dumpster/disposal fee for the NO-COMPANY-PROFILE fallback path only
// (unregistered/demo numbers where roofingPricing.js's own company-profile
// dumpster logic never runs). Included by DEFAULT - unless explicitly
// declined via job.dumpsterRequested === false.
function calculateDumpsterFee(job) {
  const included = job.dumpsterRequested !== false;
  if (!included) return { dumpsterFee: 0, dumpsterIncluded: false };
  const configuredFee = Number(process.env.ROOFING_DUMPSTER_FEE || 450);
  return { dumpsterFee: configuredFee, dumpsterIncluded: true };
}

function calculateFromCompanyPricing(job, estimatorContext) {
  if (!estimatorContext || !estimatorContext.pricing) return null;
  if (!pricingModule || typeof pricingModule.calculateRoofEstimate !== "function") return null;

  try {
    const mappedJob = mapJobForPricingEngine(job);
    const shingle = resolveShingle(estimatorContext, job.material);
    const result = pricingModule.calculateRoofEstimate(mappedJob, estimatorContext.pricing, shingle);
    if (!result || result.error) return null;
    return {
      ...result,
      source: "company-pricing-profile",
      companyName: estimatorContext.companyName,
      shingleUsed: shingle ? shingle.name : null
    };
  } catch (_) {
    return null;
  }
}

function fallbackEstimate(job) {
  const basePerSquare = Number(process.env.ROOFING_BASE_PER_SQUARE || 475);
  const designerPerSquare = Number(process.env.ROOFING_DESIGNER_PER_SQUARE || 725);
  const metalPerSquare = Number(process.env.ROOFING_METAL_PER_SQUARE || 950);
  const tilePerSquare = Number(process.env.ROOFING_TILE_PER_SQUARE || 1100);
  const slatePerSquare = Number(process.env.ROOFING_SLATE_PER_SQUARE || 1400);
  const tearOffPerSquare = Number(process.env.ROOFING_TEAROFF_PER_SQUARE || 75);
  const secondStoryPerSquare = Number(process.env.ROOFING_SECOND_STORY_PER_SQUARE || 45);

  const squares = Number(job.squares || 0);
  let perSquare = basePerSquare;

  if (/3-tab/.test(job.material || "")) perSquare = Math.max(basePerSquare - 40, 350);
  if (/designer/.test(job.material || "")) perSquare = designerPerSquare;
  if (/metal/.test(job.material || "")) perSquare = metalPerSquare;
  if (/tile/.test(job.material || "")) perSquare = tilePerSquare;
  if (/slate/.test(job.material || "")) perSquare = slatePerSquare;

  const pitchNum = parsePitchNumber(job.pitch);
  let pitchMultiplier = 1;
  if (pitchNum >= 7 && pitchNum <= 9) pitchMultiplier = 1.08;
  if (pitchNum >= 10 && pitchNum <= 12) pitchMultiplier = 1.18;
  if (pitchNum > 12) pitchMultiplier = 1.3;

  let complexityMultiplier = 1;
  if (job.complexity === "moderate") complexityMultiplier = 1.05;
  if (job.complexity === "complex") complexityMultiplier = 1.12;

  // Base structural cost (material+labor+tearoff+second-story) scales with
  // pitch/complexity multipliers - a steep or complex roof makes the CORE
  // install harder/slower.
  const baseInstall = squares * perSquare;
  const tearOffCost = squares * tearOffPerSquare * Number(job.tearOffLayers || 0);
  const secondStoryCost = Number(job.stories || 1) >= 2 ? squares * secondStoryPerSquare : 0;
  let structuralSubtotal = baseInstall + tearOffCost + secondStoryCost;
  structuralSubtotal *= pitchMultiplier;
  structuralSubtotal *= complexityMultiplier;

  // Flat-fee items (accessory flashing allowances, dumpster) are added AFTER
  // the pitch/complexity scaling - these cost roughly the same flat fee
  // regardless of roof pitch, so they should not be inflated the same way.
  const valleyPerLf = Number(process.env.ROOFING_VALLEY_PER_LF || 12);
  const detailAdders = [];
  if (job.chimneys) detailAdders.push({ name: "chimney flashing allowance", amount: Number(job.chimneys) * 250 });
  if (job.skylights) detailAdders.push({ name: "skylight flashing allowance", amount: Number(job.skylights) * 275 });
  if (job.pipeBoots) detailAdders.push({ name: "pipe boot allowance", amount: Number(job.pipeBoots) * 65 });
  if (job.valleyLf) detailAdders.push({ name: "valley flashing", amount: Number(job.valleyLf) * valleyPerLf });
  const accessoriesCost = detailAdders.reduce((sum, a) => sum + a.amount, 0);

  const { dumpsterFee, dumpsterIncluded } = calculateDumpsterFee(job);

  const subtotal = structuralSubtotal + accessoriesCost + dumpsterFee;

  const baseLow = Math.round((subtotal * 0.94) / 100) * 100;
  const baseHigh = Math.round((subtotal * 1.08) / 100) * 100;

  const { deckingLow, deckingHigh } = calculateDeckingAdder(job);

  return {
    low: baseLow,
    high: baseHigh,
    deckingLow,
    deckingHigh,
    dumpsterIncluded,
    dumpsterFeeApplied: dumpsterFee,
    totalLow: baseLow + deckingLow,
    totalHigh: baseHigh + deckingHigh,
    detailAdders,
    source: "fallback",
    breakdown: {
      materials_and_labor: Math.round(baseInstall * pitchMultiplier * complexityMultiplier),
      tearoff: Math.round(tearOffCost * pitchMultiplier * complexityMultiplier),
      ridge: 0,
      eave: 0,
      accessories: Math.round(accessoriesCost),
      dumpster: Math.round(dumpsterFee),
      second_story: Math.round(secondStoryCost * pitchMultiplier * complexityMultiplier),
      pitch_multiplier: pitchMultiplier,
      complexity_multiplier: complexityMultiplier
    }
  };
}

function calculateEstimate(job, estimatorContext) {
  const fromCompany = calculateFromCompanyPricing(job, estimatorContext);
  if (fromCompany) return fromCompany;
  return fallbackEstimate(job);
}

// Attempts a full estimate calculation only if all required fields are
// present; otherwise returns null. Used to feed the AI accurate grounding
// data every turn, regardless of whether the word "estimate" was used.
function tryCalculateEstimate(job, estimatorContext) {
  if (missingRequiredFields(job).length) return null;
  return calculateEstimate(job, estimatorContext);
}

function dollars(n) {
  if (n === null || n === undefined || Number.isNaN(Number(n))) return "$0";
  return `$${Math.round(Number(n)).toLocaleString("en-US")}`;
}

// -----------------------------------------------------------------------------
// *** THE FIX: persist the estimate + customer name/address to the database ***
// -----------------------------------------------------------------------------
//
// Called every turn a full estimate is computable AND the phone resolved to
// a real registered company (estimatorContext). Every other file in this app
// (portal.js's dashboard, /estimates page) reads customer_name/job_address
// straight out of the estimates table.
//
// INSERT vs UPDATE: the first time a given thread computes a full estimate,
// thread.dbEstimateId is null, so we INSERT and store the new row id back
// onto the thread. Every later turn for the SAME thread calls UPDATE
// against that same dbEstimateId instead of inserting a second row. If the
// UPDATE affects zero rows (e.g. someone manually cleared the estimates
// table while a thread was still in memory), we self-heal by falling back
// to a fresh INSERT.
function persistToDatabase({ estimatorContext, job, estimate, thread }) {
  if (!estimatorContext || !dbModule || typeof dbModule.saveEstimate !== "function") return;
  if (!estimate) return;

  const totalLow = estimate.totalLow ?? estimate.low;
  const totalHigh = estimate.totalHigh ?? estimate.high;
  if (totalLow == null || totalHigh == null) return;

  const estimateAmount = Math.round((Number(totalLow) + Number(totalHigh)) / 2);

  const payload = {
    company_id: estimatorContext.companyId,
    created_by_user_id: estimatorContext.user ? estimatorContext.user.id : null,
    customer_name: job.customerName || null,
    job_address: job.customerAddress || null,
    squares: job.squares || null,
    estimate_amount: estimateAmount,
    estimate_json: estimate,
    source: "sms"
  };

  try {
    if (thread.dbEstimateId && typeof dbModule.updateEstimate === "function") {
      const updated = dbModule.updateEstimate(thread.dbEstimateId, estimatorContext.companyId, payload);
      if (!updated) {
        // Row no longer exists (e.g. database was cleared mid-conversation).
        // Self-heal: insert fresh and correct the thread's pointer.
        thread.dbEstimateId = dbModule.saveEstimate(payload);
      }
      return;
    }
    thread.dbEstimateId = dbModule.saveEstimate(payload);
  } catch (err) {
    console.error("[BidBuddy SMS] Failed to persist estimate to database.", err);
  }
}

// -----------------------------------------------------------------------------
// *** PART OF THE FIX: cross-job clarification guardrail helpers ***
// -----------------------------------------------------------------------------

function describeThreadForClarification(thread, index) {
  const bits = [];
  if (thread.job.squares) bits.push(`${thread.job.squares} squares`);
  if (thread.job.pitch) bits.push(`${thread.job.pitch} pitch`);
  if (thread.job.material) bits.push(thread.job.material);
  const desc = bits.length ? bits.join(", ") : "a job with no details yet";
  return `${index + 1}) ${desc}`;
}

function buildClarificationReply(candidates) {
  const lines = [
    "I've got more than one job going on this number without a name attached yet. Which one is this for?",
    ""
  ];
  candidates.forEach((t, i) => lines.push(describeThreadForClarification(t, i)));
  lines.push("");
  lines.push("Reply with the number (1, 2, ...) or the squares count and I'll attach it.");
  return lines.join("\n");
}

// Attempts to resolve an outstanding "which job is this for?" clarification
// using the estimator's reply. Matches on a 1-based index (1, 2, ...), an
// ordinal word (first, second, ...), "last", or a squares figure that
// matches one of the candidate threads.
function resolvePendingAssignment(bucket, cleaned) {
  const pending = bucket.pendingAssignment;
  if (!pending) return null;
  const msg = lower(cleaned);
  const candidateIds = pending.candidateThreadIds || [];
  const candidates = candidateIds.map((id) => bucket.threads[id]).filter(Boolean);
  if (!candidates.length) return null;

  const ORDINAL_WORDS = [
    ["first", "1st"],
    ["second", "2nd"],
    ["third", "3rd"],
    ["fourth", "4th"],
    ["fifth", "5th"]
  ];

  const numMatch = msg.match(/\b(\d+)\b/);
  if (numMatch) {
    const n = Number(numMatch[1]);
    // Try as a 1-based index into the list first.
    if (n >= 1 && n <= candidates.length) return candidates[n - 1];
    // Otherwise try matching it as a squares figure.
    const bySquares = candidates.find((t) => Number(t.job.squares) === n);
    if (bySquares) return bySquares;
  }

  for (let i = 0; i < ORDINAL_WORDS.length && i < candidates.length; i++) {
    if (ORDINAL_WORDS[i].some((w) => msg.includes(w))) return candidates[i];
  }
  if (/\blast\b/.test(msg)) return candidates[candidates.length - 1];

  return null;
}

// -----------------------------------------------------------------------------
// Template-based reply builders — RETAINED AS FALLBACK ONLY. Used when
// OPENAI_API_KEY is not set, or the AI call fails/times out, so the SMS
// flow never goes silent in production.
// -----------------------------------------------------------------------------

function smsJoin(lines) {
  return lines
    .filter((line) => line !== null && line !== undefined && String(line).trim() !== "")
    .join("\n");
}

function bulletList(items) {
  return items.filter(Boolean).map((item) => `- ${item}`).join("\n");
}

function pricingSourceNote(estimate) {
  if (!estimate) return "";
  if (estimate.source === "company-pricing-profile") {
    return `(using ${estimate.companyName || "your"} company pricing${estimate.shingleUsed ? ", " + estimate.shingleUsed : ""})`;
  }
  return "(using generic default pricing - no company profile matched this number)";
}

function missingInfoReply(job) {
  const known = knownJobBullets(job);
  const missing = missingRequiredFields(job).map(formatFieldName);
  if (!missing.length) {
    return smsJoin([
      "I have the required items for a rough roof number.",
      "",
      "Current basis:",
      bulletList(known),
      "",
      "Helpful extras if you have them: valleys, chimneys, skylights, pipe boots, decking condition, dump access, and any flashing or ventilation changes."
    ]);
  }
  return smsJoin([
    known.length ? "Here's what I have so far:" : "I can build the roof estimate, but I need the basics first.",
    known.length ? bulletList(known) : "",
    "",
    "Still need:",
    bulletList(missing),
    "",
    "Send what you know next and I'll keep building it."
  ]);
}

function measurementReply(job, updatedFields) {
  const missing = missingRequiredFields(job).map(formatFieldName);
  const known = knownJobBullets(job);
  if (!updatedFields.length) {
    return "I'm not totally sure what to do with that yet. Send it like: 30 squares, 8/12 pitch, two story, one layer tear-off, architectural shingles.";
  }
  if (missing.length) {
    return smsJoin([
      "Got it. I updated the roof details.",
      "",
      "Current basis:",
      bulletList(known),
      "",
      "Still need to tighten the number:",
      bulletList(missing)
    ]);
  }
  return smsJoin([
    "Got it. I have enough to rough this in now.",
    "",
    "Current basis:",
    bulletList(known),
    "",
    "Send 'estimate' and I'll give you the range with assumptions and adders."
  ]);
}

function estimateReply(job, conversation) {
  const missing = missingRequiredFields(job).map(formatFieldName);
  const known = knownJobBullets(job);
  if (missing.length) {
    return smsJoin([
      "I can rough it in, but I don't want to fake a number with key items missing.",
      "",
      known.length ? "What I have:" : "",
      known.length ? bulletList(known) : "",
      "",
      "Still need:",
      bulletList(missing),
      "",
      "Send those and I'll give you a tighter range."
    ]);
  }
  const estimate = calculateEstimate(job, conversation.estimatorContext);
  conversation.lastEstimate = { ...estimate, createdAt: new Date().toISOString() };
  const hasDeckingAdder = estimate.deckingLow || estimate.deckingHigh;
  const totalLine = hasDeckingAdder
    ? `Updated rough total with decking adder: ${dollars(estimate.totalLow)} to ${dollars(estimate.totalHigh)}`
    : "";

  // Nudge for customer name/address exactly once per job, only after a real
  // estimate exists, so the job can be attributed correctly on the company
  // dashboard instead of showing up as "Untitled job".
  let customerNudge = "";
  if (!job.customerName && conversation && !conversation.askedForCustomerInfo) {
    customerNudge = job.customerAddress
      ? "Who's this for? Reply with 'customer [name]' and I'll attach it to this estimate."
      : "Who's this for, and do you have the property address? Reply with 'customer [name], [address]' and I'll save it under that job.";
    if (conversation) conversation.askedForCustomerInfo = true;
  }

  return smsJoin([
    "Here's the rough roof replacement range based on the field info:",
    "",
    "Estimate basis:",
    bulletList(known),
    "",
    `Base roof range: ${dollars(estimate.low)} to ${dollars(estimate.high)}`,
    hasDeckingAdder ? `Decking adder: ${dollars(estimate.deckingLow)} to ${dollars(estimate.deckingHigh)}` : "",
    estimate.dumpsterIncluded
      ? `Dumpster/disposal: ${dollars(estimate.dumpsterFeeApplied || 0)} included in the base range above`
      : "Dumpster/disposal: not included - customer/estimator supplying their own",
    totalLine,
    "",
    "Included assumptions:",
    bulletList([
      "normal tear-off/disposal for the layers provided",
      "standard underlayment, starter, drip edge, and ridge cap",
      "standard labor adjustment for pitch and access",
      "normal pipe boot/flashing allowance unless noted otherwise"
    ]),
    "",
    "Not included unless confirmed:",
    bulletList([
      "deck replacement beyond listed sheets",
      "structural repairs",
      "chimney flashing rebuilds",
      "skylight replacement",
      "permit or code-driven changes"
    ]),
    "",
    "If you see valleys, chimneys, skylights, or bad decking, send those next and I'll adjust it.",
    "",
    pricingSourceNote(estimate),
    customerNudge ? "" : "",
    customerNudge
  ]);
}

function explainPriceReply(job, conversation) {
  const known = knownJobBullets(job);
  const drivers = [];
  if (job.squares) drivers.push(`${job.squares} squares drives the material, labor, and disposal volume.`);
  if (job.pitch) drivers.push(`${job.pitch} pitch affects labor speed, setup, and safety.`);
  if (Number(job.stories || 1) >= 2) drivers.push("Two-story access usually adds labor and setup time.");
  if (Number(job.tearOffLayers || 0) > 0) {
    drivers.push(`${job.tearOffLayers} tear-off layer${job.tearOffLayers === 1 ? "" : "s"} adds removal and disposal.`);
  }
  if (job.material) drivers.push(`${job.material} controls a big part of the material cost.`);
  if (job.complexity === "complex") drivers.push("The roof is marked complex, so waste and labor risk are higher.");
  if (job.deckingSheets || job.deckingCondition) drivers.push("Decking should stay separate because final sheet count can change after tear-off.");
  if (!drivers.length) {
    drivers.push("The biggest roof price drivers are squares, pitch, stories/access, tear-off layers, material choice, disposal, flashing details, and decking condition.");
  }

  const missing = missingRequiredFields(job);
  const hasEstimate = conversation && conversation.lastEstimate && !missing.length;

  if (hasEstimate) {
    const current = calculateEstimate(job, conversation.estimatorContext);
    const prior = conversation.lastEstimate;
    const priorLow = Number(prior.totalLow ?? prior.low ?? 0);
    const priorHigh = Number(prior.totalHigh ?? prior.high ?? 0);
    const currentLow = Number(current.totalLow ?? current.low ?? 0);
    const currentHigh = Number(current.totalHigh ?? current.high ?? 0);
    const changed = priorLow !== currentLow || priorHigh !== currentHigh;
    if (changed) {
      return smsJoin([
        "Here's the difference:",
        "",
        `Previous range: ${dollars(priorLow)} to ${dollars(priorHigh)}`,
        `Current range: ${dollars(currentLow)} to ${dollars(currentHigh)}`,
        "",
        "On this roof:",
        bulletList(drivers),
        "",
        "That shift is coming from whatever details were added or changed since the last estimate. Send 'estimate' again any time you want the current number restated."
      ]);
    }
    return smsJoin([
      "The number hasn't actually changed since the last estimate I gave you.",
      "",
      `Current range: ${dollars(currentLow)} to ${dollars(currentHigh)}`,
      "",
      "If you were expecting a different number, let me know what changed on the job and I'll rerun it.",
      "",
      "Main drivers on this roof:",
      bulletList(drivers)
    ]);
  }

  return smsJoin([
    "The number is mainly being driven by scope, labor, and risk, not just shingles.",
    "",
    known.length ? "On this roof:" : "Typical drivers:",
    bulletList(drivers),
    "",
    "I'd present it as a rough replacement range until decking, flashing, and hidden conditions are confirmed."
  ]);
}

function lowerPriceReply() {
  return smsJoin([
    "Maybe, but I wouldn't cut waterproofing items just to make the number look better.",
    "",
    "Safer places to review:",
    bulletList([
      "shingle product level",
      "whether ventilation changes are included",
      "dump/disposal assumptions",
      "whether decking is separate instead of buried in the base",
      "scope differences versus another bid"
    ]),
    "",
    "I would not remove drip edge, starter, underlayment, flashing, or required ice/water protection just to lower the price."
  ]);
}

function deckingReply(job, conversation) {
  const lines = [
    "I'd keep decking separate from the base roof number unless the sheet count is already confirmed.",
    "",
    "Best structure:",
    bulletList([
      "base roof replacement covers normal tear-off and install",
      "decking is listed as a per-sheet or allowance adder",
      "final decking quantity is confirmed after tear-off"
    ])
  ];
  if (job.deckingSheets) {
    const estimate = calculateEstimate(job, conversation.estimatorContext);
    lines.push("");
    lines.push(`I have ${job.deckingSheets} decking sheet${job.deckingSheets === 1 ? "" : "s"} noted as an adder.`);
    lines.push(`Current decking adder: ${dollars(estimate.deckingLow)} to ${dollars(estimate.deckingHigh)}`);
  } else if (job.deckingCondition) {
    lines.push("");
    lines.push("You mentioned suspect decking. Send the number of sheets if you have it. If not, I'd call it out as a per-sheet adder after tear-off.");
  } else {
    lines.push("");
    lines.push("Send the number of sheets, square footage, or a note like 'soft decking around eaves' and I'll treat it as a separate adder.");
  }
  return smsJoin(lines);
}

function scopeDetailReply(job) {
  return smsJoin([
    "Good callout. Details like chimneys, skylights, pipe boots, valleys, ventilation, and flashing can move the number.",
    "",
    "What I have noted:",
    bulletList(knownJobBullets(job).length ? knownJobBullets(job) : ["no detailed roof accessories captured yet"]),
    "",
    "If you can, send counts like: 2 chimneys, 1 skylight, 6 pipe boots, 40 LF valley. I'll adjust the estimate around those details."
  ]);
}

function homeownerHelpReply(job, conversation) {
  const hasFullEstimate = !missingRequiredFields(job).length;
  if (!hasFullEstimate) {
    return smsJoin([
      "Here's a safe way to say it before the number is fully tightened:",
      "",
      "'I'm still confirming a few roof details, but the final price will depend on the roof size, pitch, tear-off, access, material choice, and any hidden decking or flashing issues we find.'",
      "",
      "Once you send the missing basics, I'll help you word the actual range."
    ]);
  }
  const range = calculateEstimate(job, conversation.estimatorContext);
  return smsJoin([
    "Here's how I'd explain it to the homeowner:",
    "",
    `Based on what we can see today, this roof is likely in the ${dollars(range.totalLow)} to ${dollars(range.totalHigh)} range. That includes the roof replacement, tear-off, disposal, standard accessories, and labor for the pitch and access. The final number can change if we uncover bad decking, hidden damage, or flashing issues after tear-off.`,
    "",
    "That gives them a real number without locking you into hidden conditions."
  ]);
}

function competitorReply() {
  return smsJoin([
    "I'd compare scope, not just the total price.",
    "",
    "Ask if the cheaper bid includes:",
    bulletList([
      "tear-off and disposal",
      "drip edge, starter, underlayment, and ridge cap",
      "ice/water where required",
      "flashing details",
      "decking adders",
      "permit assumptions",
      "ventilation changes",
      "warranty terms"
    ]),
    "",
    "A cheaper bid may be fine, but only if the scope is actually the same."
  ]);
}

function fieldChecklistReply() {
  return smsJoin([
    "Before you leave, I'd check these items:",
    "",
    bulletList([
      "confirm squares or roof measurement",
      "confirm pitch",
      "confirm one-story or two-story access",
      "confirm tear-off layers",
      "note shingle/material choice",
      "count chimneys, skylights, pipe boots, and valleys",
      "look for soft decking, waves, or leak areas",
      "confirm dump access and driveway limitations",
      "note flashing and ventilation concerns"
    ]),
    "",
    "Those are the items most likely to change the rough number after you leave the property."
  ]);
}

function insuranceReply() {
  return smsJoin([
    "For insurance or supplement work, I'd keep the wording scope-based and factual.",
    "",
    "Use language like:",
    "'Estimate includes roof replacement scope observed in the field. Final scope may change based on tear-off findings, decking condition, flashing requirements, and code or permit requirements.'",
    "",
    "I wouldn't promise coverage or approval. Keep it to observed damage, measured scope, and clearly listed assumptions."
  ]);
}

function helpReply() {
  return smsJoin([
    "I can help you build and explain a rough roof estimate from the field.",
    "",
    "Send details like:",
    bulletList([
      "30 squares",
      "8/12 pitch",
      "two story",
      "one layer tear-off",
      "architectural shingles",
      "2 chimneys, 1 skylight, 6 pipe boots",
      "add 10 sheets decking"
    ]),
    "",
    "You can also ask: estimate, what am I missing, why so high, explain to homeowner, competitor is cheaper, or field checklist."
  ]);
}

function generalRoofingReply(job) {
  return smsJoin([
    "I can help with that from an estimating angle.",
    "",
    "For this roof, I'm focused on the details that affect price: squares, pitch, access, tear-off, material, decking, flashing, ventilation, and roof complexity.",
    "",
    missingRequiredFields(job).length
      ? "If you want a number, send the missing basics and I'll tighten the range."
      : "If you want, send 'estimate' and I'll price the current scope."
  ]);
}

function unclearReply(job) {
  return smsJoin([
    "I may need that one a little clearer.",
    "",
    "You can send it like:",
    "30 squares, 8/12 pitch, two story, one layer tear-off, architectural shingles",
    "",
    missingRequiredFields(job).length
      ? "Or ask 'what am I missing' and I'll list the next items I need."
      : "Or send 'estimate' and I'll price what we have."
  ]);
}

function buildTemplateReply(intent, job, conversation, updatedFields) {
  switch (intent) {
    case "reset_estimate":
      conversation.job = emptyRoofJob();
      conversation.lastEstimate = null;
      return "Got it. I cleared this roof and started fresh. Send the squares, pitch, stories, tear-off layers, and shingle choice when you're ready.";
    case "help":
      return helpReply();
    case "provide_measurement":
      return measurementReply(job, updatedFields || []);
    case "request_estimate":
      return estimateReply(job, conversation);
    case "explain_price":
      return explainPriceReply(job, conversation);
    case "lower_price":
      return lowerPriceReply();
    case "decking":
      return deckingReply(job, conversation);
    case "scope_detail":
      return scopeDetailReply(job);
    case "missing_info":
      return missingInfoReply(job);
    case "homeowner_response_help":
      return homeownerHelpReply(job, conversation);
    case "competitor_comparison":
      return competitorReply();
    case "field_checklist":
      return fieldChecklistReply();
    case "insurance_or_supplement":
      return insuranceReply();
    case "general_roofing_question":
      return generalRoofingReply(job);
    case "unclear":
    default:
      return unclearReply(job);
  }
}

// -----------------------------------------------------------------------------
// Telnyx outbound send
// -----------------------------------------------------------------------------

async function sendSms({ to, from, text }) {
  const apiKey = process.env.TELNYX_API_KEY;
  const telnyxFrom = from || process.env.TELNYX_PHONE_NUMBER || process.env.SMS_FROM_NUMBER;

  if (!apiKey || !telnyxFrom || !to) {
    console.log("[BidBuddy SMS] Outbound skipped. Missing TELNYX_API_KEY, from number, or recipient.");
    console.log("[BidBuddy SMS] Reply would have been:", text);
    return { skipped: true, reason: "missing_telnyx_config" };
  }

  const response = await fetch("https://api.telnyx.com/v2/messages", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({ from: telnyxFrom, to, text })
  });

  const responseBody = await response.text();
  if (!response.ok) {
    console.error("[BidBuddy SMS] Telnyx send failed", response.status, responseBody);
    return { ok: false, status: response.status, body: responseBody };
  }
  return { ok: true, status: response.status, body: responseBody };
}

// -----------------------------------------------------------------------------
// Public processing function
// -----------------------------------------------------------------------------

async function processIncomingSms({ from, to, text, companyId }) {
  const cleaned = cleanText(text);
  // Computed once, up front, so every early-return (compliance gate) and
  // the main flow below all report the SAME phone-level key.
  const phoneKey = getPhoneKey({ from, companyId });

  // -------------------- Compliance gate: deterministic, unchanged --------------------
  if (matchesKeyword(cleaned, OPT_OUT_KEYWORDS)) {
    const knownCompany = resolveEstimatorContext(from);
    recordOptOut(from, knownCompany ? knownCompany.companyId : null);
    return { reply: OPT_OUT_MESSAGE, intent: "opt_out", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: false, replySource: "compliance" };
  }
  if (matchesKeyword(cleaned, HELP_KEYWORDS)) {
    return { reply: HELP_MESSAGE, intent: "help_keyword", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: false, replySource: "compliance" };
  }
  if (matchesKeyword(cleaned, OPT_IN_KEYWORDS)) {
    const knownCompany = resolveEstimatorContext(from);
    recordOptIn(from, knownCompany ? knownCompany.companyId : null);
    return { reply: OPT_IN_MESSAGE, intent: "opt_in", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: false, replySource: "compliance" };
  }
  if (isOptedOut(from)) {
    return { reply: null, intent: "suppressed_opted_out", job: null, conversationKey: phoneKey, estimatorContext: null, suppressed: true, replySource: "compliance" };
  }

  // -------------------- Normal conversation flow --------------------
  const bucket = getOrCreatePhoneBucket(phoneKey);

  if (bucket.estimatorContext === null) {
    bucket.estimatorContext = resolveEstimatorContext(from) || false;
  }
  const estimatorContext = bucket.estimatorContext || null;

  const details = parseRoofDetails(cleaned);
  const intent = classifyIntent(cleaned, details);

  // *** PART OF THE FIX: resolve an outstanding "which job is this for?"
  // clarification BEFORE anything else touches conversation state, so a
  // clarifying answer is never accidentally treated as a new job or
  // merged into the wrong thread. ***
  if (bucket.pendingAssignment) {
    const resolvedThread = resolvePendingAssignment(bucket, cleaned);
    if (resolvedThread) {
      const pending = bucket.pendingAssignment;
      if (pending.name) {
        resolvedThread.job.customerName = pending.name;
        resolvedThread.customerKey = normalizeCustomerKey(pending.name);
      }
      if (pending.address) {
        resolvedThread.job.customerAddress = pending.address;
      }
      resolvedThread.updatedAt = new Date().toISOString();
      bucket.activeThreadId = resolvedThread.id;
      bucket.pendingAssignment = null;

      if (resolvedThread.lastEstimate && estimatorContext) {
        persistToDatabase({ estimatorContext, job: resolvedThread.job, estimate: resolvedThread.lastEstimate, thread: resolvedThread });
      }

      const reply = `Got it - attached to the ${resolvedThread.job.squares ? resolvedThread.job.squares + " square " : ""}job. Send anything else on that one, or start the next job's details.`;
      resolvedThread.messages.push({
        at: new Date().toISOString(),
        from,
        to,
        inbound: cleaned,
        intent: "clarification_resolved",
        updatedFields: ["customerName", "customerAddress"],
        reply,
        replySource: "deterministic_clarification"
      });
      if (resolvedThread.messages.length > MAX_STORED_MESSAGES) {
        resolvedThread.messages = resolvedThread.messages.slice(-MAX_STORED_MESSAGES);
      }

      bucket.threads[resolvedThread.id] = resolvedThread;
      bucket.updatedAt = new Date().toISOString();
      conversationState[phoneKey] = bucket;
      saveState(conversationState);

      return {
        reply,
        intent: "clarification_resolved",
        job: resolvedThread.job,
        conversationKey: phoneKey,
        threadId: resolvedThread.id,
        estimatorContext: estimatorContext ? { companyId: estimatorContext.companyId, companyName: estimatorContext.companyName } : null,
        suppressed: false,
        replySource: "deterministic_clarification"
      };
    }
    // If it didn't resolve, fall through - this message may be unrelated
    // (e.g. a brand new job's own measurements), and the pending question
    // can still be answered later; we don't want to block normal work.
  }

  // *** PART OF THE FIX: a bare customer name/address message (no
  // measurements of its own) that doesn't match an existing customer by
  // name or address is genuinely ambiguous if MORE THAN ONE job on this
  // phone is currently missing a name. Rather than guessing (which is
  // what caused customer/address mixing on real jobs), ask ONE short
  // clarifying question and hold the info until answered. ***
  if (isBareCustomerInfoMessage(details)) {
    const alreadyMatchedByName = details.customerName ? findThreadByCustomerName(bucket, details.customerName) : null;
    const alreadyMatchedByAddress =
      !alreadyMatchedByName && details.customerAddress ? findThreadByCustomerAddress(bucket, details.customerAddress) : null;

    if (!alreadyMatchedByName && !alreadyMatchedByAddress) {
      const needingName = findThreadsNeedingCustomerName(bucket);
      if (needingName.length > 1) {
        bucket.pendingAssignment = {
          name: details.customerName || null,
          address: details.customerAddress || null,
          candidateThreadIds: needingName.map((t) => t.id),
          createdAt: new Date().toISOString()
        };
        const reply = buildClarificationReply(needingName);
        bucket.updatedAt = new Date().toISOString();
        conversationState[phoneKey] = bucket;
        saveState(conversationState);
        return {
          reply,
          intent: "clarify_customer_job",
          job: null,
          conversationKey: phoneKey,
          threadId: null,
          estimatorContext: estimatorContext ? { companyId: estimatorContext.companyId, companyName: estimatorContext.companyName } : null,
          suppressed: false,
          replySource: "deterministic_clarification"
        };
      }
    }
  }

  // "reset" is a state-mutating action, kept deterministic on purpose so it
  // always works reliably even if the AI call fails. It clears whatever
  // thread is CURRENTLY active on this phone in place - it does not touch
  // any of this phone's other, separate customer threads.
  if (intent === "reset_estimate") {
    let thread = bucket.activeThreadId ? bucket.threads[bucket.activeThreadId] : null;
    if (!thread) {
      thread = emptyThread();
      bucket.threads[thread.id] = thread;
      bucket.activeThreadId = thread.id;
    }
    thread.job = emptyRoofJob();
    thread.lastEstimate = null;
    thread.dbEstimateId = null; // starting a brand new job needs a brand new dashboard row
    thread.customerKey = null;
    thread.askedForCustomerInfo = false;
    const reply = "Got it. I cleared this roof and started fresh. Send the squares, pitch, stories, tear-off layers, and shingle choice when you're ready.";
    thread.updatedAt = new Date().toISOString();
    thread.messages.push({ at: new Date().toISOString(), from, to, inbound: cleaned, intent, updatedFields: [], reply });
    bucket.updatedAt = new Date().toISOString();
    conversationState[phoneKey] = bucket;
    saveState(conversationState);
    return { reply, intent, job: thread.job, conversationKey: phoneKey, threadId: thread.id, estimatorContext: null, suppressed: false, replySource: "deterministic_reset" };
  }

  // Route this message to the correct customer thread for this phone -
  // this is the core of multi-job-per-phone tracking. See
  // resolveActiveThread() above for the full rule set.
  const conversation = resolveActiveThread(bucket, cleaned, details);
  conversation.estimatorContext = estimatorContext;

  let updatedFields = [];
  updatedFields = mergeJobDetails(conversation.job, details);

  // Keep this thread's customer-lookup key in sync the moment a name lands
  // on it, so a LATER message that mentions this same customer by name
  // (after switching away to a different customer) can find its way back.
  if (conversation.job.customerName) {
    conversation.customerKey = normalizeCustomerKey(conversation.job.customerName);
  }

  // Always compute the estimate silently if the required fields are present,
  // regardless of whether the estimator actually asked for one this turn.
  // This gives the AI accurate grounding data for ANY question about price.
  const previousEstimate = conversation.lastEstimate || null;
  const currentEstimate = tryCalculateEstimate(conversation.job, estimatorContext);

  let reply = null;
  let replySource = "template_fallback";

  if (aiReplyModule && typeof aiReplyModule.generateAiReply === "function") {
    const recentHistory = (conversation.messages || []).slice(-MAX_AI_HISTORY_TURNS);
    try {
      const aiText = await aiReplyModule.generateAiReply({
        companyName: estimatorContext ? estimatorContext.companyName : null,
        job: conversation.job,
        missingFields: missingRequiredFields(conversation.job),
        currentEstimate,
        previousEstimate,
        askedForCustomerInfo: conversation.askedForCustomerInfo,
        pricingProfile: estimatorContext ? estimatorContext.pricing : null,
        history: recentHistory,
        userText: cleaned
      });
      if (aiText) {
        reply = aiText;
        replySource = "ai";
        // Mirror the template-fallback nudge tracking: once a real estimate
        // exists and the customer name is still unknown, mark it as asked so
        // neither path re-nags on every subsequent message in this job.
        if (currentEstimate && !conversation.job.customerName && !conversation.askedForCustomerInfo) {
          conversation.askedForCustomerInfo = true;
        }
      }
    } catch (_) {
      // fall through to template fallback below
    }
  }

  if (!reply) {
    reply = buildTemplateReply(intent, conversation.job, conversation, updatedFields);
    replySource = "template_fallback";
  }

  // Keep lastEstimate current for future delta comparisons regardless of
  // which reply path was used, as long as we could actually compute one.
  if (currentEstimate) {
    conversation.lastEstimate = { ...currentEstimate, createdAt: new Date().toISOString() };
  }

  // *** THE FIX: write this thread's estimate (and customer name/address) to
  // the database every turn a full estimate exists, so the company
  // dashboard always reflects the latest known customer info for this job.
  // This runs identically for every company/tenant since it is keyed
  // purely off estimatorContext.companyId, resolved earlier from the
  // phone number. ***
  if (currentEstimate && estimatorContext) {
    persistToDatabase({ estimatorContext, job: conversation.job, estimate: conversation.lastEstimate, thread: conversation });
  }

  conversation.updatedAt = new Date().toISOString();
  conversation.messages.push({ at: new Date().toISOString(), from, to, inbound: cleaned, intent, updatedFields, reply, replySource });
  if (conversation.messages.length > MAX_STORED_MESSAGES) {
    conversation.messages = conversation.messages.slice(-MAX_STORED_MESSAGES);
  }

  // Write this thread back into the bucket and keep it marked active -
  // resolveActiveThread() may have switched threads mid-message (e.g. an
  // implicit new job start), so this is not always a no-op.
  bucket.threads[conversation.id] = conversation;
  bucket.activeThreadId = conversation.id;
  bucket.updatedAt = new Date().toISOString();
  pruneOldThreads(bucket);

  conversationState[phoneKey] = bucket;
  saveState(conversationState);

  return {
    reply,
    intent,
    job: conversation.job,
    conversationKey: phoneKey,
    threadId: conversation.id,
    estimatorContext: estimatorContext ? { companyId: estimatorContext.companyId, companyName: estimatorContext.companyName } : null,
    suppressed: false,
    replySource
  };
}

// -----------------------------------------------------------------------------
// Express route handler
// -----------------------------------------------------------------------------

async function handleSms(req, res) {
  try {
    const body = req && req.body ? req.body : {};

    if (!isProcessableInboundEvent(body)) {
      // Telnyx status callback for our own outbound message (message.sent /
      // message.finalized) - acknowledge without treating it as new inbound.
      if (res) return res.status(200).json({ ok: true, ignored: true });
      return { ok: true, ignored: true };
    }

    const payload = extractSmsPayload(req);
    const { from, to, text } = payload;

    if (!from || !text) {
      if (res) return res.status(200).json({ ok: true, skipped: "missing_from_or_text" });
      return { ok: true, skipped: true };
    }

    const companyContext = resolveEstimatorContext(from);
    const companyId = companyContext ? companyContext.companyId : null;

    const result = await processIncomingSms({ from, to, text, companyId });

    if (result.reply) {
      await sendSms({ to: from, from: to, text: result.reply });
    }

    if (res) {
      return res.status(200).json({ ok: true, intent: result.intent, replySource: result.replySource, suppressed: result.suppressed });
    }
    return result;
  } catch (error) {
    console.error("[BidBuddy SMS] handler error", error);
    if (res) return res.status(200).json({ ok: false, error: "sms_handler_error" });
    return { ok: false, error };
  }
}

// -----------------------------------------------------------------------------
// Exports
// -----------------------------------------------------------------------------

module.exports = {
  handleSms,
  processIncomingSms,
  parseRoofDetails,
  classifyIntent,
  calculateEstimate,
  emptyRoofJob,
  missingRequiredFields,
  normalizePhone,
  isOptedOut,
  recordOptOut,
  recordOptIn
};
